import type { Player, Pos, Squad } from "./types";

type Raw = [string, number, Pos[], number];

function club(name: string, year: number, league: string, rows: Raw[]): Squad {
  const id = `${name}-${year}`;
  const used = new Set<number>();
  const seen = new Set<string>();
  return {
    id,
    nation: name,
    year,
    league,
    players: rows.map(([pname, num, pos, ovr], i) => {
      let n = num;
      while (used.has(n)) n += 1;
      used.add(n);
      let pid = `${id}-${n}-${pname}`;
      if (seen.has(pid)) pid = `${pid}-${i}`;
      seen.add(pid);
      return {
        id: pid,
        name: pname,
        nation: name,
        year,
        num: n,
        pos,
        ovr,
      };
    }),
  };
}

/** Historic XIs from the top five leagues, 1980 onward. */
export const CLUB_SQUADS: Squad[] = [
  club("Nottingham Forest", 1980, "First Division", [
    ["Shilton", 1, ["GK"], 90],
    ["Anderson", 2, ["RB"], 82],
    ["Needham", 5, ["CB"], 84],
    ["Burns", 6, ["CB"], 85],
    ["Gray", 3, ["LB"], 83],
    ["McGovern", 8, ["CM", "DM"], 84],
    ["O'Neill", 11, ["RM", "RW"], 83],
    ["Bowyer", 4, ["CM"], 82],
    ["Robertson", 7, ["LW", "LM"], 88],
    ["Francis", 10, ["ST", "AM"], 86],
    ["Birtles", 9, ["ST"], 84],
    ["Woodcock", 12, ["ST"], 83],
  ]),
  club("Liverpool", 1984, "First Division", [
    ["Grobbelaar", 1, ["GK"], 86],
    ["Neal", 2, ["RB"], 84],
    ["Lawrenson", 6, ["CB"], 88],
    ["Hansen", 4, ["CB"], 90],
    ["Kennedy", 3, ["LB"], 82],
    ["Lee", 8, ["CM"], 83],
    ["Souness", 11, ["CM", "DM"], 91],
    ["Whelan", 5, ["CM"], 84],
    ["Dalglish", 7, ["ST", "AM"], 93],
    ["Rush", 9, ["ST"], 92],
    ["Johnston", 10, ["LW", "ST"], 84],
    ["Nicol", 14, ["RB", "CM"], 83],
  ]),
  club("Liverpool", 2005, "Premier League", [
    ["Dudek", 1, ["GK"], 84],
    ["Finnan", 3, ["RB"], 82],
    ["Carragher", 23, ["CB"], 86],
    ["Hyypiä", 4, ["CB"], 85],
    ["Riise", 6, ["LB"], 83],
    ["Hamann", 16, ["DM"], 84],
    ["Gerrard", 8, ["CM", "AM"], 92],
    ["Xabi Alonso", 14, ["CM", "DM"], 88],
    ["Luis García", 10, ["AM", "ST"], 84],
    ["Baroš", 5, ["ST"], 82],
    ["Cissé", 9, ["ST"], 83],
    ["Kewell", 7, ["LW", "AM"], 84],
    ["Traoré", 21, ["LB", "RB"], 80],
  ]),
  club("Liverpool", 2019, "Premier League", [
    ["Alisson", 1, ["GK"], 91],
    ["Alexander-Arnold", 66, ["RB"], 88],
    ["van Dijk", 4, ["CB"], 93],
    ["Matip", 32, ["CB"], 84],
    ["Robertson", 26, ["LB"], 88],
    ["Fabinho", 3, ["DM"], 88],
    ["Wijnaldum", 5, ["CM"], 85],
    ["Henderson", 14, ["CM", "DM"], 85],
    ["Salah", 11, ["RW", "ST"], 92],
    ["Firmino", 9, ["ST", "AM"], 88],
    ["Mané", 10, ["LW", "ST"], 91],
    ["Oxlade-Chamberlain", 15, ["CM", "RW"], 82],
  ]),
  club("Manchester United", 1999, "Premier League", [
    ["Schmeichel", 1, ["GK"], 92],
    ["G. Neville", 2, ["RB"], 85],
    ["Stam", 6, ["CB"], 90],
    ["Johnsen", 5, ["CB"], 84],
    ["Irwin", 3, ["LB"], 86],
    ["Keane", 16, ["CM", "DM"], 91],
    ["Scholes", 18, ["CM", "AM"], 90],
    ["Beckham", 7, ["RM", "CM"], 90],
    ["Giggs", 11, ["LM", "LW"], 90],
    ["Yorke", 19, ["ST"], 88],
    ["Cole", 9, ["ST"], 87],
    ["Solskjær", 20, ["ST"], 84],
    ["Butt", 8, ["CM", "DM"], 83],
  ]),
  club("Manchester United", 2008, "Premier League", [
    ["van der Sar", 1, ["GK"], 90],
    ["Brown", 2, ["RB", "CB"], 82],
    ["Ferdinand", 5, ["CB"], 90],
    ["Vidic", 15, ["CB"], 90],
    ["Evra", 3, ["LB"], 87],
    ["Carrick", 16, ["CM", "DM"], 86],
    ["Scholes", 18, ["CM"], 88],
    ["Ronaldo", 7, ["RW", "LW", "ST"], 94],
    ["Giggs", 11, ["LM", "AM"], 86],
    ["Rooney", 10, ["ST", "AM"], 91],
    ["Tevez", 32, ["ST", "AM"], 88],
    ["Hargreaves", 4, ["DM", "CM"], 84],
    ["Nani", 17, ["RW", "LW"], 83],
  ]),
  club("Arsenal", 2004, "Premier League", [
    ["Lehmann", 1, ["GK"], 86],
    ["Lauren", 12, ["RB"], 84],
    ["Campbell", 23, ["CB"], 90],
    ["Toure", 28, ["CB", "DM"], 86],
    ["Cole", 3, ["LB"], 88],
    ["Vieira", 4, ["CM", "DM"], 92],
    ["Gilberto", 19, ["DM", "CM"], 86],
    ["Ljungberg", 8, ["RM", "RW"], 86],
    ["Pires", 7, ["LM", "LW", "AM"], 88],
    ["Bergkamp", 10, ["AM", "ST"], 91],
    ["Henry", 14, ["ST", "LW"], 94],
    ["Reyes", 9, ["LW", "ST"], 84],
  ]),
  club("Chelsea", 2005, "Premier League", [
    ["Čech", 1, ["GK"], 91],
    ["Paulo Ferreira", 20, ["RB"], 82],
    ["Carvalho", 6, ["CB"], 88],
    ["Terry", 26, ["CB"], 90],
    ["Gallas", 13, ["CB", "RB"], 85],
    ["Makelele", 4, ["DM"], 90],
    ["Lampard", 8, ["CM", "AM"], 91],
    ["J. Cole", 10, ["RW", "AM"], 84],
    ["Duff", 11, ["LW", "LM"], 85],
    ["Drogba", 15, ["ST"], 90],
    ["Gudjohnsen", 22, ["ST", "AM"], 84],
    ["Robben", 16, ["RW", "LW"], 88],
  ]),
  club("Chelsea", 2012, "Premier League", [
    ["Čech", 1, ["GK"], 88],
    ["Bosingwa", 17, ["RB"], 80],
    ["Cahill", 24, ["CB"], 84],
    ["Terry", 26, ["CB"], 87],
    ["Cole", 3, ["LB"], 86],
    ["Mikel", 12, ["DM"], 82],
    ["Lampard", 8, ["CM"], 86],
    ["Ramires", 7, ["CM", "RW"], 84],
    ["Mata", 10, ["AM", "RW"], 88],
    ["Drogba", 11, ["ST"], 88],
    ["Kalou", 21, ["ST", "RW"], 82],
    ["Meireles", 16, ["CM"], 83],
  ]),
  club("Leicester", 2016, "Premier League", [
    ["Schmeichel", 1, ["GK"], 84],
    ["Simpson", 17, ["RB"], 78],
    ["Morgan", 5, ["CB"], 80],
    ["Huth", 6, ["CB"], 82],
    ["Fuchs", 28, ["LB"], 80],
    ["Drinkwater", 4, ["CM"], 80],
    ["Kante", 14, ["DM", "CM"], 88],
    ["Mahrez", 26, ["RW", "AM"], 86],
    ["Albrighton", 11, ["LW", "LM"], 80],
    ["Okazaki", 20, ["ST", "AM"], 80],
    ["Vardy", 9, ["ST"], 86],
    ["King", 10, ["CM", "AM"], 78],
  ]),
  club("Manchester City", 2023, "Premier League", [
    ["Ederson", 31, ["GK"], 89],
    ["Walker", 2, ["RB"], 86],
    ["Dias", 3, ["CB"], 89],
    ["Akanji", 25, ["CB"], 84],
    ["Aké", 6, ["CB", "LB"], 84],
    ["Rodri", 16, ["DM"], 91],
    ["De Bruyne", 17, ["AM", "CM"], 92],
    ["Gündoğan", 8, ["CM", "AM"], 88],
    ["Bernardo", 20, ["RW", "AM"], 88],
    ["Haaland", 9, ["ST"], 91],
    ["Grealish", 10, ["LW", "LM"], 85],
    ["Foden", 47, ["LW", "AM", "RW"], 88],
  ]),
  club("Everton", 1985, "First Division", [
    ["Southall", 1, ["GK"], 90],
    ["Stevens", 2, ["RB"], 82],
    ["Mountfield", 5, ["CB"], 82],
    ["Ratcliffe", 6, ["CB"], 84],
    ["Van Den Hauwe", 3, ["LB"], 82],
    ["Reid", 4, ["CM", "DM"], 85],
    ["Bracewell", 8, ["CM"], 82],
    ["Steven", 7, ["RM", "RW"], 83],
    ["Sheedy", 11, ["LM", "LW"], 84],
    ["Sharp", 9, ["ST"], 85],
    ["Gray", 10, ["ST"], 84],
    ["Heath", 12, ["ST", "AM"], 82],
  ]),
  club("Real Madrid", 2002, "La Liga", [
    ["Casillas", 1, ["GK"], 90],
    ["Michel Salgado", 2, ["RB"], 84],
    ["Hierro", 4, ["CB", "DM"], 90],
    ["Helguera", 6, ["CB", "DM"], 84],
    ["Roberto Carlos", 3, ["LB"], 93],
    ["Makelele", 24, ["DM"], 88],
    ["Figo", 10, ["RW", "AM"], 92],
    ["Zidane", 5, ["AM", "CM"], 96],
    ["Raúl", 7, ["ST", "AM"], 92],
    ["Morientes", 9, ["ST"], 86],
    ["McManaman", 8, ["RW", "CM"], 84],
    ["Solari", 21, ["LM", "CM"], 82],
  ]),
  club("Real Madrid", 2017, "La Liga", [
    ["Navas", 1, ["GK"], 86],
    ["Carvajal", 2, ["RB"], 86],
    ["Varane", 5, ["CB"], 88],
    ["Ramos", 4, ["CB"], 91],
    ["Marcelo", 12, ["LB"], 88],
    ["Casemiro", 14, ["DM"], 88],
    ["Modrić", 19, ["CM", "AM"], 91],
    ["Kroos", 8, ["CM"], 90],
    ["Bale", 11, ["RW", "ST"], 90],
    ["Benzema", 9, ["ST"], 89],
    ["Ronaldo", 7, ["LW", "ST"], 94],
    ["Isco", 22, ["AM", "LW"], 86],
  ]),
  club("Real Madrid", 2014, "La Liga", [
    ["Casillas", 1, ["GK"], 88],
    ["Carvajal", 2, ["RB"], 84],
    ["Pepe", 3, ["CB"], 88],
    ["Ramos", 4, ["CB"], 90],
    ["Marcelo", 12, ["LB"], 86],
    ["Coentrão", 15, ["LB"], 84],
    ["Xabi Alonso", 14, ["DM"], 89],
    ["Modrić", 19, ["CM"], 90],
    ["Di María", 22, ["RW", "AM"], 90],
    ["Bale", 11, ["RW", "ST"], 91],
    ["Benzema", 9, ["ST"], 88],
    ["Ronaldo", 7, ["LW", "ST"], 94],
    ["Isco", 23, ["AM"], 85],
  ]),
  club("Real Madrid", 2015, "La Liga", [
    ["Navas", 1, ["GK"], 85],
    ["Carvajal", 2, ["RB"], 85],
    ["Pepe", 3, ["CB"], 87],
    ["Ramos", 4, ["CB"], 90],
    ["Marcelo", 12, ["LB"], 87],
    ["Kroos", 8, ["CM"], 89],
    ["Modrić", 19, ["CM"], 90],
    ["James", 10, ["AM", "RW"], 88],
    ["Bale", 11, ["RW"], 90],
    ["Benzema", 9, ["ST"], 88],
    ["Ronaldo", 7, ["LW", "ST"], 93],
    ["Isco", 22, ["AM"], 86],
    ["Varane", 5, ["CB"], 85],
  ]),
  club("Real Madrid", 2016, "La Liga", [
    ["Navas", 1, ["GK"], 86],
    ["Carvajal", 2, ["RB"], 86],
    ["Pepe", 3, ["CB"], 86],
    ["Ramos", 4, ["CB"], 91],
    ["Marcelo", 12, ["LB"], 88],
    ["Casemiro", 14, ["DM"], 86],
    ["Modrić", 19, ["CM"], 91],
    ["Kroos", 8, ["CM"], 90],
    ["Bale", 11, ["RW"], 89],
    ["Benzema", 9, ["ST"], 88],
    ["Ronaldo", 7, ["LW", "ST"], 94],
    ["Isco", 22, ["AM", "LW"], 86],
    ["Varane", 5, ["CB"], 86],
  ]),
  club("Real Madrid", 2022, "La Liga", [
    ["Courtois", 1, ["GK"], 91],
    ["Carvajal", 2, ["RB"], 85],
    ["Militão", 3, ["CB"], 86],
    ["Alaba", 4, ["CB", "LB"], 86],
    ["Mendy", 23, ["LB"], 84],
    ["Casemiro", 14, ["DM"], 88],
    ["Modrić", 10, ["CM"], 88],
    ["Kroos", 8, ["CM"], 88],
    ["Valverde", 15, ["CM", "RW"], 86],
    ["Benzema", 9, ["ST"], 91],
    ["Vinícius", 20, ["LW"], 88],
    ["Rodrygo", 21, ["RW", "ST"], 84],
  ]),
  club("Barcelona", 1992, "La Liga", [
    ["Zubizarreta", 1, ["GK"], 88],
    ["Ferrer", 2, ["RB"], 84],
    ["Koeman", 4, ["CB"], 90],
    ["Nando", 5, ["CB"], 80],
    ["Juan Carlos", 3, ["LB"], 80],
    ["Guardiola", 6, ["DM", "CM"], 86],
    ["Eusebio", 16, ["CM"], 82],
    ["Bakero", 10, ["AM", "CM"], 85],
    ["Laudrup", 9, ["AM", "RW"], 90],
    ["Stoichkov", 8, ["ST", "LW"], 90],
    ["Begiristain", 11, ["LW"], 84],
    ["Salinas", 19, ["ST"], 82],
  ]),
  club("Barcelona", 2009, "La Liga", [
    ["Valdés", 1, ["GK"], 86],
    ["Alves", 2, ["RB"], 90],
    ["Piqué", 3, ["CB"], 88],
    ["Puyol", 5, ["CB", "RB"], 90],
    ["Abidal", 22, ["LB", "CB"], 84],
    ["Busquets", 16, ["DM"], 88],
    ["Xavi", 6, ["CM"], 93],
    ["Iniesta", 8, ["CM", "AM", "LW"], 92],
    ["Messi", 10, ["RW", "AM", "ST"], 95],
    ["Eto'o", 9, ["ST"], 90],
    ["Henry", 14, ["LW", "ST"], 88],
    ["Touré", 24, ["DM", "CM"], 86],
  ]),
  club("Barcelona", 2015, "La Liga", [
    ["Bravo", 13, ["GK"], 84],
    ["Alves", 22, ["RB"], 86],
    ["Piqué", 3, ["CB"], 88],
    ["Mascherano", 14, ["CB", "DM"], 86],
    ["Alba", 18, ["LB"], 86],
    ["Busquets", 5, ["DM"], 88],
    ["Rakitic", 4, ["CM"], 86],
    ["Iniesta", 8, ["CM", "AM"], 90],
    ["Messi", 10, ["RW", "ST", "AM"], 94],
    ["Suárez", 9, ["ST"], 92],
    ["Neymar", 11, ["LW", "ST"], 92],
    ["Pedro", 7, ["RW", "LW"], 84],
  ]),
  club("Atlético Madrid", 2014, "La Liga", [
    ["Courtois", 13, ["GK"], 88],
    ["Juanfran", 20, ["RB"], 84],
    ["Miranda", 23, ["CB"], 84],
    ["Godín", 2, ["CB"], 88],
    ["Filipe Luís", 3, ["LB"], 86],
    ["Gabi", 14, ["CM", "DM"], 84],
    ["Tiago", 5, ["CM", "DM"], 83],
    ["Koke", 6, ["CM", "AM"], 85],
    ["Arda", 10, ["LW", "AM"], 84],
    ["Diego Costa", 19, ["ST"], 88],
    ["Villa", 9, ["ST", "LW"], 86],
    ["Raúl García", 8, ["AM", "CM"], 82],
  ]),
  club("Valencia", 2004, "La Liga", [
    ["Cañizares", 1, ["GK"], 88],
    ["Curro Torres", 2, ["RB"], 80],
    ["Ayala", 4, ["CB"], 86],
    ["Marchena", 5, ["CB"], 84],
    ["Carboni", 3, ["LB"], 82],
    ["Albelda", 6, ["DM"], 86],
    ["Baraja", 8, ["CM"], 86],
    ["Rufete", 7, ["RM", "RW"], 82],
    ["Vicente", 14, ["LW", "LM"], 85],
    ["Aimar", 10, ["AM"], 88],
    ["Mista", 9, ["ST"], 82],
    ["Angulo", 11, ["ST", "RW"], 80],
  ]),
  club("AC Milan", 1989, "Serie A", [
    ["Galli", 1, ["GK"], 86],
    ["Tassotti", 2, ["RB"], 86],
    ["Baresi", 6, ["CB"], 94],
    ["Costacurta", 5, ["CB"], 88],
    ["Maldini", 3, ["LB", "CB"], 90],
    ["Ancelotti", 4, ["CM"], 86],
    ["Rijkaard", 8, ["DM", "CM"], 90],
    ["Donadoni", 16, ["RW", "RM"], 86],
    ["Gullit", 10, ["AM", "ST", "CM"], 92],
    ["van Basten", 9, ["ST"], 94],
    ["Evani", 11, ["LW", "CM"], 82],
    ["Colombo", 7, ["CM"], 80],
  ]),
  club("AC Milan", 2007, "Serie A", [
    ["Dida", 1, ["GK"], 86],
    ["Oddo", 44, ["RB"], 82],
    ["Nesta", 13, ["CB"], 90],
    ["Maldini", 3, ["CB", "LB"], 90],
    ["Jankulovski", 18, ["LB"], 82],
    ["Gattuso", 8, ["DM", "CM"], 86],
    ["Pirlo", 21, ["CM", "DM"], 91],
    ["Ambrosini", 23, ["CM", "DM"], 84],
    ["Seedorf", 10, ["CM", "AM"], 86],
    ["Kaká", 22, ["AM"], 92],
    ["Inzaghi", 9, ["ST"], 86],
    ["Gilardino", 11, ["ST"], 84],
  ]),
  club("Juventus", 1996, "Serie A", [
    ["Peruzzi", 1, ["GK"], 88],
    ["Ferrara", 2, ["RB", "CB"], 84],
    ["Montero", 4, ["CB"], 86],
    ["Torricelli", 5, ["CB", "RB"], 82],
    ["Pessotto", 3, ["LB"], 82],
    ["Davids", 26, ["DM", "CM"], 88],
    ["Deschamps", 7, ["DM", "CM"], 86],
    ["Conte", 8, ["CM"], 84],
    ["Zidane", 21, ["AM"], 92],
    ["Del Piero", 10, ["ST", "AM", "LW"], 90],
    ["Vialli", 9, ["ST"], 86],
    ["Ravanelli", 11, ["ST"], 85],
  ]),
  club("Juventus", 2015, "Serie A", [
    ["Buffon", 1, ["GK"], 90],
    ["Lichtsteiner", 26, ["RB"], 82],
    ["Bonucci", 19, ["CB"], 88],
    ["Chiellini", 3, ["CB"], 90],
    ["Evra", 33, ["LB"], 82],
    ["Pirlo", 21, ["CM", "DM"], 86],
    ["Marchisio", 8, ["CM"], 86],
    ["Pogba", 6, ["CM", "AM"], 88],
    ["Vidal", 23, ["CM", "DM"], 88],
    ["Tevez", 10, ["ST", "AM"], 88],
    ["Morata", 9, ["ST"], 84],
    ["Pereyra", 20, ["AM", "CM"], 82],
  ]),
  club("Inter", 2010, "Serie A", [
    ["Júlio César", 12, ["GK"], 88],
    ["Maicon", 13, ["RB"], 90],
    ["Lucio", 6, ["CB"], 88],
    ["Samuel", 25, ["CB"], 86],
    ["Zanetti", 4, ["RB", "CM", "LB"], 86],
    ["Cambiasso", 19, ["DM", "CM"], 86],
    ["Motta", 8, ["CM"], 84],
    ["Sneijder", 10, ["AM", "CM"], 90],
    ["Eto'o", 9, ["ST", "RW"], 90],
    ["Milito", 22, ["ST"], 88],
    ["Pandev", 27, ["LW", "ST"], 82],
    ["Chivu", 26, ["LB", "CB"], 82],
  ]),
  club("Inter", 2023, "Serie A", [
    ["Onana", 24, ["GK"], 86],
    ["Darmian", 36, ["RB", "CB"], 82],
    ["Acerbi", 15, ["CB"], 84],
    ["Bastoni", 95, ["CB"], 86],
    ["Dimarco", 32, ["LB", "LWB"], 84],
    ["Çalhanoğlu", 20, ["CM", "AM"], 86],
    ["Barella", 23, ["CM"], 88],
    ["Mkhitaryan", 22, ["CM", "AM"], 84],
    ["Dumfries", 2, ["RWB", "RB"], 84],
    ["Lautaro", 10, ["ST"], 88],
    ["Džeko", 9, ["ST"], 84],
    ["Brozović", 77, ["DM"], 86],
  ]),
  club("Napoli", 1987, "Serie A", [
    ["Garella", 1, ["GK"], 82],
    ["Ferrario", 2, ["RB", "CB"], 80],
    ["Renica", 5, ["CB"], 80],
    ["Francini", 3, ["LB"], 82],
    ["De Napoli", 4, ["CM", "DM"], 84],
    ["Bagni", 6, ["CM"], 80],
    ["Maradona", 10, ["AM", "ST"], 98],
    ["Careca", 9, ["ST"], 90],
    ["Giordano", 11, ["ST", "LW"], 84],
    ["Bruscolotti", 13, ["RB"], 80],
    ["Volpecina", 7, ["RW"], 78],
    ["Carnevale", 8, ["ST"], 80],
  ]),
  club("Napoli", 2023, "Serie A", [
    ["Meret", 1, ["GK"], 84],
    ["Di Lorenzo", 22, ["RB"], 86],
    ["Kim", 13, ["CB"], 86],
    ["Rrahmani", 5, ["CB"], 84],
    ["Olivera", 17, ["LB"], 82],
    ["Lobotka", 68, ["CM", "DM"], 86],
    ["Anguissa", 99, ["CM", "DM"], 84],
    ["Zielinski", 20, ["CM", "AM"], 84],
    ["Politano", 21, ["RW"], 84],
    ["Osimhen", 9, ["ST"], 88],
    ["Kvaratskhelia", 77, ["LW"], 88],
    ["Elmas", 7, ["AM", "CM"], 82],
  ]),
  club("Roma", 2001, "Serie A", [
    ["Antonioli", 1, ["GK"], 82],
    ["Cafu", 2, ["RB"], 90],
    ["Samuel", 18, ["CB"], 84],
    ["Aldair", 6, ["CB"], 86],
    ["Candela", 3, ["LB"], 84],
    ["Diamantini", 5, ["DM"], 80],
    ["Tommasi", 17, ["CM"], 82],
    ["Emerson", 11, ["CM", "DM"], 86],
    ["Totti", 10, ["AM", "ST"], 90],
    ["Montella", 9, ["ST"], 86],
    ["Batistuta", 20, ["ST"], 90],
    ["Nakata", 8, ["AM", "CM"], 82],
  ]),
  club("Bayern Munich", 2001, "Bundesliga", [
    ["Kahn", 1, ["GK"], 92],
    ["Sagnol", 2, ["RB"], 84],
    ["Linke", 5, ["CB"], 82],
    ["Kuffour", 4, ["CB"], 84],
    ["Lizarazu", 3, ["LB"], 86],
    ["Effenberg", 11, ["CM", "AM"], 88],
    ["Jeremies", 16, ["DM", "CM"], 84],
    ["Hargreaves", 23, ["DM", "CM"], 82],
    ["Salihamidžić", 20, ["RW", "RM"], 84],
    ["Élber", 9, ["ST"], 88],
    ["Jancker", 10, ["ST"], 84],
    ["Scholl", 7, ["AM", "RW"], 86],
  ]),
  club("Bayern Munich", 2013, "Bundesliga", [
    ["Neuer", 1, ["GK"], 92],
    ["Lahm", 21, ["RB", "DM"], 92],
    ["Boateng", 17, ["CB"], 88],
    ["Dante", 4, ["CB"], 84],
    ["Alaba", 27, ["LB", "CM"], 86],
    ["Javi Martínez", 8, ["DM", "CB"], 86],
    ["Schweinsteiger", 31, ["CM"], 90],
    ["Kroos", 39, ["CM", "AM"], 86],
    ["Robben", 10, ["RW"], 92],
    ["Mandžukić", 9, ["ST"], 86],
    ["Ribéry", 7, ["LW"], 91],
    ["Müller", 25, ["AM", "ST"], 88],
    ["Gómez", 33, ["ST"], 86],
  ]),
  club("Bayern Munich", 2020, "Bundesliga", [
    ["Neuer", 1, ["GK"], 90],
    ["Pavard", 5, ["RB", "CB"], 84],
    ["Boateng", 17, ["CB"], 84],
    ["Alaba", 27, ["CB", "LB"], 86],
    ["Davies", 19, ["LB"], 86],
    ["Kimmich", 32, ["DM", "RB"], 90],
    ["Goretzka", 18, ["CM"], 86],
    ["Thiago", 6, ["CM"], 88],
    ["Gnabry", 7, ["RW", "LW"], 86],
    ["Lewandowski", 9, ["ST"], 93],
    ["Coman", 29, ["LW", "RW"], 86],
    ["Müller", 25, ["AM", "ST"], 88],
  ]),
  club("Borussia Dortmund", 1997, "Bundesliga", [
    ["Klos", 1, ["GK"], 84],
    ["Reuter", 7, ["RB", "CB"], 84],
    ["Kree", 5, ["CB"], 82],
    ["Sammer", 6, ["CB", "DM"], 90],
    ["Feiersinger", 3, ["LB"], 80],
    ["Lambert", 4, ["CM"], 82],
    ["Zorc", 8, ["CM"], 84],
    ["Heinrich", 17, ["RM", "RW"], 82],
    ["Möller", 10, ["AM"], 88],
    ["Chapuisat", 9, ["ST"], 86],
    ["Riedle", 13, ["ST"], 84],
    ["Herrlich", 11, ["ST"], 82],
  ]),
  club("Borussia Dortmund", 2013, "Bundesliga", [
    ["Weidenfeller", 1, ["GK"], 84],
    ["Piszczek", 26, ["RB"], 86],
    ["Subotić", 4, ["CB"], 84],
    ["Hummels", 15, ["CB"], 88],
    ["Schmelzer", 29, ["LB"], 82],
    ["Bender", 6, ["DM", "CM"], 84],
    ["Gündoğan", 8, ["CM", "AM"], 86],
    ["Mkhitaryan", 10, ["AM", "RW"], 84],
    ["Blaszczykowski", 16, ["RW"], 84],
    ["Lewandowski", 9, ["ST"], 90],
    ["Reus", 11, ["LW", "AM", "ST"], 88],
    ["Grosskreutz", 19, ["LW", "LM"], 80],
  ]),
  club("Bayer Leverkusen", 2024, "Bundesliga", [
    ["Hrádecký", 1, ["GK"], 84],
    ["Frimpong", 30, ["RB", "RWB"], 86],
    ["Tah", 4, ["CB"], 86],
    ["Tapsoba", 12, ["CB"], 84],
    ["Grimaldo", 20, ["LB", "LWB"], 86],
    ["Xhaka", 34, ["DM", "CM"], 86],
    ["Palacios", 25, ["CM", "DM"], 84],
    ["Wirtz", 10, ["AM", "CM"], 88],
    ["Adli", 21, ["AM", "ST"], 82],
    ["Boniface", 22, ["ST"], 84],
    ["Hofmann", 7, ["RW", "AM"], 84],
    ["Tella", 19, ["RW", "LW"], 82],
  ]),
  club("Hamburg", 1983, "Bundesliga", [
    ["Stein", 1, ["GK"], 86],
    ["Kaltz", 2, ["RB"], 88],
    ["Hieronymus", 4, ["CB"], 82],
    ["Jakobs", 5, ["CB"], 82],
    ["Wehmeyer", 3, ["LB"], 80],
    ["Magath", 10, ["CM", "AM"], 88],
    ["Hartwig", 8, ["CM"], 82],
    ["Milewski", 6, ["DM"], 80],
    ["von Heesen", 11, ["RW", "AM"], 82],
    ["Hrubesch", 9, ["ST"], 86],
    ["Bastrup", 7, ["ST", "LW"], 82],
    ["Rolff", 15, ["CM"], 80],
  ]),
  club("Marseille", 1993, "Division 1", [
    ["Barthez", 16, ["GK"], 86],
    ["Angloma", 2, ["RB"], 84],
    ["Boli", 5, ["CB"], 86],
    ["Di Meco", 3, ["LB"], 82],
    ["Desailly", 4, ["CB", "DM"], 88],
    ["Sauzée", 8, ["CM"], 84],
    ["Deschamps", 7, ["DM", "CM"], 86],
    ["Pelé", 6, ["CM"], 80],
    ["Völler", 9, ["ST"], 88],
    ["Boksic", 11, ["ST"], 86],
    ["Ferreri", 10, ["AM", "ST"], 82],
    ["Eydelie", 15, ["CM"], 80],
  ]),
  club("Monaco", 2017, "Ligue 1", [
    ["Subašić", 1, ["GK"], 84],
    ["Sidibé", 38, ["RB"], 82],
    ["Glik", 25, ["CB"], 84],
    ["Jemerson", 5, ["CB"], 80],
    ["Mendy", 23, ["LB"], 82],
    ["Fabinho", 2, ["DM", "RB"], 86],
    ["Bakayoko", 14, ["DM", "CM"], 82],
    ["Bernardo", 10, ["AM", "RW"], 86],
    ["Lemar", 27, ["LW", "AM"], 84],
    ["Mbappé", 29, ["ST", "RW"], 88],
    ["Falcao", 9, ["ST"], 86],
    ["Germain", 18, ["ST"], 80],
  ]),
  club("Lyon", 2008, "Ligue 1", [
    ["Coupet", 1, ["GK"], 86],
    ["Réveillère", 4, ["RB"], 82],
    ["Cris", 3, ["CB"], 84],
    ["Squillaci", 5, ["CB"], 82],
    ["Abidal", 20, ["LB"], 86],
    ["Juninho", 8, ["CM", "AM"], 88],
    ["Toulalan", 6, ["DM", "CM"], 84],
    ["Kallstrom", 29, ["CM"], 82],
    ["Govou", 14, ["RW", "ST"], 84],
    ["Benzema", 10, ["ST"], 86],
    ["Malouda", 11, ["LW", "CM"], 84],
    ["Baroš", 9, ["ST"], 82],
  ]),
  club("PSG", 2021, "Ligue 1", [
    ["Navas", 1, ["GK"], 86],
    ["Florenzi", 24, ["RB"], 80],
    ["Marquinhos", 5, ["CB", "DM"], 88],
    ["Kimpembe", 3, ["CB"], 84],
    ["Kurzawa", 20, ["LB"], 78],
    ["Paredes", 8, ["DM", "CM"], 82],
    ["Verratti", 6, ["CM"], 88],
    ["Gueye", 27, ["DM"], 84],
    ["Messi", 30, ["RW", "AM", "ST"], 93],
    ["Mbappé", 7, ["ST", "LW"], 93],
    ["Neymar", 10, ["LW", "AM", "ST"], 91],
    ["Di María", 11, ["RW", "AM"], 86],
    ["Hakimi", 2, ["RB", "RWB"], 86],
  ]),
  club("Lille", 2021, "Ligue 1", [
    ["Maignan", 16, ["GK"], 86],
    ["Celik", 2, ["RB"], 80],
    ["Fonte", 6, ["CB"], 82],
    ["Botman", 4, ["CB"], 82],
    ["Reinildo", 28, ["LB"], 80],
    ["André", 21, ["DM", "CM"], 82],
    ["Xeka", 8, ["CM"], 80],
    ["Renato Sanches", 18, ["CM", "AM"], 84],
    ["Bamba", 7, ["LW", "RW"], 82],
    ["Yilmaz", 17, ["ST"], 84],
    ["David", 9, ["ST"], 84],
    ["Ikoné", 10, ["RW", "AM"], 80],
  ]),
  club("Bordeaux", 1987, "Division 1", [
    ["Dropsy", 1, ["GK"], 82],
    ["Thouvenel", 2, ["RB"], 80],
    ["Specht", 4, ["CB"], 82],
    ["Dominguez", 5, ["CB"], 80],
    ["Girard", 3, ["LB"], 80],
    ["Tigana", 6, ["CM", "DM"], 88],
    ["Giresse", 10, ["AM", "CM"], 90],
    ["Lacombe", 8, ["CM"], 82],
    ["Vercruysse", 7, ["RW"], 80],
    ["Pasqualetti", 11, ["LW"], 78],
    ["Ferreri", 9, ["ST"], 82],
    ["Dréossi", 14, ["CM"], 78],
  ]),
  club("Aston Villa", 1982, "First Division", [
    ["Rimmer", 1, ["GK"], 84],
    ["Swain", 2, ["RB"], 80],
    ["McNaught", 4, ["CB"], 82],
    ["Evans", 5, ["CB"], 82],
    ["Williams", 3, ["LB"], 80],
    ["Mortimer", 10, ["CM"], 84],
    ["Cowans", 7, ["CM", "AM"], 86],
    ["Bremner", 8, ["CM"], 82],
    ["Shaw", 9, ["ST"], 84],
    ["Withe", 11, ["ST"], 84],
    ["Morley", 12, ["RW"], 82],
    ["Geddis", 14, ["ST"], 78],
  ]),
  club("Ipswich", 1981, "First Division", [
    ["Cooper", 1, ["GK"], 84],
    ["Burley", 2, ["RB"], 82],
    ["Osman", 6, ["CB"], 84],
    ["Butcher", 5, ["CB"], 86],
    ["Mills", 3, ["LB", "RB"], 84],
    ["Thijssen", 8, ["CM", "AM"], 86],
    ["Wark", 10, ["CM", "ST"], 86],
    ["Mühren", 11, ["CM", "AM"], 88],
    ["Brazil", 7, ["RW", "ST"], 82],
    ["Mariner", 9, ["ST"], 86],
    ["Gates", 12, ["AM", "ST"], 80],
  ]),
  club("Blackburn", 1995, "Premier League", [
    ["Flowers", 1, ["GK"], 86],
    ["Berg", 2, ["RB", "CB"], 82],
    ["Hendry", 5, ["CB"], 86],
    ["Kenna", 20, ["CB", "RB"], 80],
    ["Le Saux", 3, ["LB"], 84],
    ["Sherwood", 4, ["CM"], 84],
    ["Batty", 6, ["DM", "CM"], 84],
    ["Ripley", 7, ["RM", "RW"], 80],
    ["Wilcox", 11, ["LM", "LW"], 82],
    ["Shearer", 9, ["ST"], 92],
    ["Sutton", 10, ["ST"], 86],
    ["Marker", 12, ["CB"], 78],
  ]),
  club("Leeds", 1992, "First Division", [
    ["Lukic", 1, ["GK"], 84],
    ["Newsome", 2, ["RB", "CB"], 80],
    ["Fairclough", 5, ["CB"], 82],
    ["Whyte", 6, ["CB"], 82],
    ["Dorigo", 3, ["LB"], 84],
    ["Batty", 4, ["DM", "CM"], 84],
    ["McAllister", 11, ["CM", "AM"], 86],
    ["Strachan", 8, ["RM", "CM"], 86],
    ["Speed", 7, ["CM", "LM"], 84],
    ["Cantona", 10, ["ST", "AM"], 90],
    ["Chapman", 9, ["ST"], 84],
    ["Wallace", 12, ["ST", "RW"], 80],
  ]),
  club("Tottenham", 2019, "Premier League", [
    ["Lloris", 1, ["GK"], 88],
    ["Trippier", 2, ["RB"], 84],
    ["Alderweireld", 4, ["CB"], 86],
    ["Vertonghen", 5, ["CB"], 86],
    ["Davies", 33, ["LB"], 80],
    ["Sissoko", 17, ["CM", "DM"], 82],
    ["Winks", 8, ["CM"], 80],
    ["Eriksen", 23, ["AM", "CM"], 88],
    ["Son", 7, ["LW", "ST"], 88],
    ["Kane", 10, ["ST"], 91],
    ["Lucas", 27, ["RW", "AM"], 84],
    ["Alli", 20, ["AM"], 84],
  ]),
  club("Arsenal", 1998, "Premier League", [
    ["Seaman", 1, ["GK"], 90],
    ["Dixon", 2, ["RB"], 84],
    ["Adams", 6, ["CB"], 90],
    ["Keown", 5, ["CB"], 86],
    ["Winterburn", 3, ["LB"], 84],
    ["Vieira", 4, ["CM", "DM"], 90],
    ["Petit", 17, ["DM", "CM"], 88],
    ["Overmars", 11, ["LW", "RW"], 86],
    ["Bergkamp", 10, ["AM", "ST"], 92],
    ["Anelka", 9, ["ST"], 86],
    ["Parlour", 15, ["CM", "RM"], 82],
    ["Wright", 8, ["ST"], 84],
  ]),
  club("Athletic Club", 1984, "La Liga", [
    ["Zubizarreta", 1, ["GK"], 86],
    ["Urquiaga", 2, ["RB"], 82],
    ["Goikoetxea", 5, ["CB"], 86],
    ["Liceranzu", 6, ["CB"], 82],
    ["De Andrés", 4, ["CM", "DM"], 82],
    ["Gallego", 8, ["CM"], 84],
    ["Urtubi", 10, ["AM", "CM"], 82],
    ["Dani", 7, ["ST", "AM"], 84],
    ["Argote", 11, ["LW"], 82],
    ["Sola", 9, ["ST"], 82],
    ["Núñez", 3, ["LB"], 80],
    ["Sarabia", 14, ["ST"], 80],
  ]),
  club("Real Sociedad", 1982, "La Liga", [
    ["Arconada", 1, ["GK"], 90],
    ["Górriz", 2, ["CB"], 82],
    ["Kortabarria", 5, ["CB"], 82],
    ["Olaizola", 3, ["LB"], 80],
    ["Diego", 4, ["RB", "CB"], 80],
    ["Alonso", 8, ["CM"], 84],
    ["Zamora", 10, ["AM", "CM"], 84],
    ["López Ufarte", 7, ["RW", "AM"], 86],
    ["Satrústegui", 9, ["ST"], 86],
    ["Uralde", 11, ["ST"], 84],
    ["Bakero", 12, ["AM", "ST"], 80],
    ["Celayeta", 6, ["RB"], 78],
  ]),
  club("Deportivo", 2000, "La Liga", [
    ["Molina", 1, ["GK"], 86],
    ["Manuel Pablo", 2, ["RB"], 84],
    ["Naybet", 5, ["CB"], 86],
    ["Donato", 4, ["CB", "DM"], 84],
    ["Romero", 3, ["LB"], 82],
    ["Mauro Silva", 6, ["DM"], 88],
    ["Flavio", 8, ["CM"], 82],
    ["Valerón", 21, ["AM"], 88],
    ["Fran", 11, ["LM", "AM"], 84],
    ["Makaay", 9, ["ST"], 88],
    ["Djalminha", 10, ["AM", "RW"], 86],
    ["Pandiani", 12, ["ST"], 82],
  ]),
  club("Sevilla", 2006, "La Liga", [
    ["Palop", 1, ["GK"], 84],
    ["Daniel Alves", 4, ["RB"], 86],
    ["Javi Navarro", 2, ["CB"], 82],
    ["Palacios", 6, ["CB"], 80],
    ["David", 3, ["LB"], 80],
    ["Poulsen", 8, ["DM", "CM"], 82],
    ["Martí", 7, ["CM"], 80],
    ["Renato", 11, ["CM", "AM"], 84],
    ["Jesús Navas", 17, ["RW"], 84],
    ["Kanouté", 9, ["ST"], 86],
    ["Luís Fabiano", 10, ["ST"], 86],
    ["Maresca", 25, ["CM", "AM"], 80],
  ]),
  club("Sampdoria", 1991, "Serie A", [
    ["Pagliuca", 1, ["GK"], 86],
    ["Mannini", 2, ["RB"], 82],
    ["Vierchowod", 6, ["CB"], 88],
    ["Katanec", 5, ["CB", "DM"], 82],
    ["Lanna", 3, ["LB"], 80],
    ["Pari", 4, ["DM", "CM"], 82],
    ["Lombardo", 7, ["RW"], 86],
    ["Cerezo", 8, ["CM"], 84],
    ["Vialli", 9, ["ST"], 88],
    ["Mancini", 10, ["ST", "AM"], 90],
    ["Dossena", 11, ["LM", "CM"], 80],
    ["Bonetti", 12, ["CM"], 78],
  ]),
  club("Lazio", 2000, "Serie A", [
    ["Marchegiani", 1, ["GK"], 84],
    ["Pancaro", 2, ["RB", "LB"], 82],
    ["Nesta", 13, ["CB"], 92],
    ["Mihajlović", 11, ["CB"], 86],
    ["Negro", 5, ["CB", "RB"], 82],
    ["Sensini", 6, ["DM", "CB"], 84],
    ["Verón", 23, ["CM", "AM"], 90],
    ["Simeone", 14, ["DM", "CM"], 86],
    ["Nedvěd", 18, ["LM", "AM"], 90],
    ["Salas", 9, ["ST"], 88],
    ["Bokšić", 21, ["ST"], 84],
    ["Conceição", 7, ["RW"], 84],
  ]),
  club("Parma", 1999, "Serie A", [
    ["Buffon", 1, ["GK"], 88],
    ["Thuram", 2, ["RB", "CB"], 90],
    ["Cannavaro", 17, ["CB"], 88],
    ["Sensini", 6, ["CB", "DM"], 84],
    ["Benarrivo", 3, ["LB", "RB"], 82],
    ["Verón", 11, ["CM", "AM"], 88],
    ["Dino Baggio", 7, ["DM", "CM"], 84],
    ["Fuser", 8, ["RM", "CM"], 82],
    ["Chiesa", 18, ["ST", "RW"], 86],
    ["Crespo", 9, ["ST"], 90],
    ["Balbo", 10, ["ST"], 84],
    ["Boghossian", 5, ["DM"], 82],
  ]),
  club("Fiorentina", 1999, "Serie A", [
    ["Toldo", 1, ["GK"], 88],
    ["Repka", 2, ["RB", "CB"], 80],
    ["Padalino", 4, ["CB"], 80],
    ["Firicano", 5, ["CB"], 80],
    ["Torricelli", 6, ["LB", "RB"], 82],
    ["Rui Costa", 10, ["AM"], 90],
    ["Cois", 15, ["CM", "DM"], 80],
    ["Heinrich", 8, ["RM", "RW"], 82],
    ["Edmundo", 7, ["ST", "AM"], 86],
    ["Batistuta", 9, ["ST"], 92],
    ["Robbiati", 11, ["LW", "AM"], 80],
    ["Rossitto", 16, ["DM"], 78],
  ]),
  club("Werder Bremen", 2004, "Bundesliga", [
    ["Reinke", 1, ["GK"], 82],
    ["Owomoyela", 2, ["RB"], 80],
    ["Ismaël", 5, ["CB"], 84],
    ["Pasanen", 4, ["CB"], 80],
    ["Valdez", 3, ["LB", "CB"], 80],
    ["Frings", 22, ["DM", "CM"], 86],
    ["Ernst", 8, ["CM"], 82],
    ["Micoud", 10, ["AM", "CM"], 86],
    ["Borowski", 6, ["CM", "AM"], 82],
    ["Klasnić", 9, ["ST"], 84],
    ["Aílton", 11, ["ST"], 86],
    ["Krstajić", 24, ["CB"], 82],
  ]),
  club("Stuttgart", 2007, "Bundesliga", [
    ["Hildebrand", 1, ["GK"], 84],
    ["Osorio", 3, ["RB"], 80],
    ["Tasci", 5, ["CB"], 82],
    ["Delpierre", 6, ["CB"], 82],
    ["Magnin", 21, ["LB"], 80],
    ["Hilbert", 19, ["RM", "RB"], 80],
    ["Khedira", 28, ["CM", "DM"], 84],
    ["Pardo", 8, ["CM", "AM"], 82],
    ["Cacau", 18, ["ST", "RW"], 82],
    ["Gómez", 33, ["ST"], 86],
    ["Hitzlsperger", 11, ["CM"], 84],
    ["Meissner", 7, ["RW"], 78],
  ]),
  club("Kaiserslautern", 1998, "Bundesliga", [
    ["Koch", 1, ["GK"], 82],
    ["Roos", 2, ["RB"], 78],
    ["Kadlec", 5, ["CB"], 82],
    ["Ramzy", 4, ["CB"], 80],
    ["Hengen", 3, ["LB", "CB"], 80],
    ["Schjønberg", 6, ["DM", "CM"], 80],
    ["Sforza", 10, ["CM", "AM"], 86],
    ["Buck", 7, ["RM"], 80],
    ["Reich", 21, ["AM", "RW"], 80],
    ["Marschall", 9, ["ST"], 84],
    ["Kuka", 11, ["ST", "LW"], 84],
    ["Hristov", 8, ["CM"], 80],
  ]),
  club("Saint-Étienne", 1981, "Division 1", [
    ["Castaneda", 1, ["GK"], 84],
    ["Janvion", 2, ["RB", "CB"], 82],
    ["Lopez", 4, ["CB"], 82],
    ["Repellini", 5, ["CB"], 80],
    ["Battiston", 3, ["LB", "CB"], 86],
    ["Larios", 8, ["CM"], 84],
    ["Platini", 10, ["AM"], 94],
    ["Roussillon", 11, ["LW", "LM"], 82],
    ["Paganelli", 7, ["RW"], 80],
    ["Rep", 9, ["ST"], 86],
    ["Lestage", 6, ["DM", "CM"], 80],
    ["Zimako", 12, ["ST", "RW"], 80],
  ]),
  club("Nantes", 1995, "Division 1", [
    ["Martini", 1, ["GK"], 82],
    ["Le Dizet", 2, ["RB"], 80],
    ["Karembeu", 6, ["CM", "RB"], 84],
    ["N'Doram", 4, ["CB", "DM"], 82],
    ["Pedros", 3, ["LB", "LM"], 82],
    ["Makelele", 5, ["DM"], 84],
    ["Cauet", 7, ["CM"], 80],
    ["Ferri", 10, ["AM", "CM"], 82],
    ["Ouédec", 9, ["ST"], 82],
    ["Loko", 11, ["ST", "LW"], 84],
    ["N'Diaye", 8, ["CM"], 80],
    ["Carotti", 12, ["CB"], 78],
  ]),
  club("Auxerre", 1996, "Division 1", [
    ["Cool", 1, ["GK"], 82],
    ["Goma", 4, ["CB"], 82],
    ["Silvestre", 5, ["CB"], 84],
    ["Mahé", 3, ["LB"], 80],
    ["Verlaat", 6, ["CB", "DM"], 82],
    ["Saib", 10, ["AM", "CM"], 84],
    ["Lamouchi", 7, ["CM"], 82],
    ["Cocard", 8, ["RW", "AM"], 82],
    ["Guivarc'h", 11, ["ST"], 84],
    ["Laslandes", 9, ["ST"], 82],
    ["Rabesandratana", 2, ["RB", "CM"], 80],
    ["Guéret", 14, ["CM"], 78],
  ]),
  club("PSG", 1994, "Division 1", [
    ["Lama", 1, ["GK"], 86],
    ["Bravo", 2, ["RB"], 82],
    ["Kombouaré", 4, ["CB"], 82],
    ["Ricardo", 5, ["CB"], 84],
    ["Colleter", 3, ["LB"], 80],
    ["Le Guen", 6, ["DM", "CM"], 84],
    ["Guérin", 8, ["CM"], 82],
    ["Valdo", 7, ["AM", "CM"], 86],
    ["Ginola", 11, ["LW", "AM"], 86],
    ["Weah", 9, ["ST"], 90],
    ["Raí", 10, ["AM"], 88],
    ["Roche", 16, ["CB"], 80],
  ]),
  club("Montpellier", 2012, "Ligue 1", [
    ["Jourdren", 1, ["GK"], 80],
    ["Bocaly", 2, ["RB"], 78],
    ["Hilton", 3, ["CB"], 82],
    ["Yanga-Mbiwa", 4, ["CB"], 82],
    ["Bedimo", 5, ["LB"], 80],
    ["Saihi", 13, ["DM"], 80],
    ["Stambouli", 14, ["DM", "CM"], 80],
    ["Cabella", 11, ["AM", "RW"], 82],
    ["Belhanda", 10, ["AM", "CM"], 84],
    ["Giroud", 9, ["ST"], 86],
    ["Utaka", 7, ["RW", "ST"], 80],
    ["Camara", 19, ["ST"], 78],
  ]),
  club("Barcelona", 2011, "La Liga", [
    ["Valdés", 1, ["GK"], 89],
    ["Alves", 2, ["RB"], 88],
    ["Piqué", 3, ["CB"], 88],
    ["Puyol", 5, ["CB"], 88],
    ["Abidal", 22, ["LB"], 84],
    ["Busquets", 16, ["DM"], 88],
    ["Xavi", 6, ["CM"], 92],
    ["Iniesta", 8, ["AM", "CM"], 91],
    ["Pedro", 17, ["RW", "LW"], 84],
    ["Villa", 7, ["ST", "LW"], 88],
    ["Messi", 10, ["RW", "ST", "AM"], 94],
    ["Keita", 15, ["CM"], 82],
    ["Mascherano", 14, ["CB", "DM"], 85],
  ]),
  club("Manchester City", 2019, "Premier League", [
    ["Ederson", 31, ["GK"], 89],
    ["Walker", 2, ["RB"], 85],
    ["Stones", 5, ["CB"], 84],
    ["Laporte", 14, ["CB"], 86],
    ["Mendy", 22, ["LB"], 82],
    ["Fernandinho", 25, ["DM"], 85],
    ["De Bruyne", 17, ["AM", "CM"], 91],
    ["Silva", 21, ["AM", "CM"], 88],
    ["Bernardo", 20, ["RW", "AM"], 87],
    ["Sterling", 7, ["LW", "RW"], 88],
    ["Agüero", 10, ["ST"], 90],
    ["Sané", 19, ["LW"], 86],
    ["Gündoğan", 8, ["CM"], 84],
  ]),
  club("Chelsea", 2021, "Premier League", [
    ["Mendy", 16, ["GK"], 87],
    ["Azpilicueta", 28, ["RB", "CB"], 84],
    ["Silva", 6, ["CB"], 86],
    ["Rüdiger", 2, ["CB"], 85],
    ["Chilwell", 21, ["LB"], 82],
    ["Kanté", 7, ["DM", "CM"], 90],
    ["Jorginho", 5, ["DM"], 85],
    ["Mount", 19, ["AM", "CM"], 84],
    ["Havertz", 29, ["AM", "ST"], 84],
    ["Werner", 11, ["LW", "ST"], 83],
    ["Lukaku", 9, ["ST"], 86],
    ["Pulisic", 10, ["RW", "LW"], 82],
    ["James", 24, ["RB", "RWB"], 84],
  ]),
  club("Juventus", 2017, "Serie A", [
    ["Buffon", 1, ["GK"], 90],
    ["Dani Alves", 23, ["RB"], 86],
    ["Bonucci", 19, ["CB"], 88],
    ["Barzagli", 15, ["CB"], 85],
    ["Alex Sandro", 12, ["LB"], 85],
    ["Khedira", 6, ["CM"], 84],
    ["Pjanic", 5, ["CM", "AM"], 86],
    ["Marchisio", 8, ["CM"], 84],
    ["Dybala", 21, ["AM", "ST"], 88],
    ["Mandzukic", 17, ["ST"], 84],
    ["Higuaín", 9, ["ST"], 88],
    ["Cuadrado", 16, ["RW", "RWB"], 83],
    ["Chiellini", 3, ["CB"], 88],
  ]),
  club("AC Milan", 1994, "Serie A", [
    ["Rossi", 1, ["GK"], 86],
    ["Tassotti", 2, ["RB"], 86],
    ["Costacurta", 5, ["CB"], 88],
    ["Baresi", 6, ["CB", "DM"], 92],
    ["Maldini", 3, ["LB", "CB"], 93],
    ["Desailly", 4, ["DM", "CB"], 90],
    ["Albertini", 8, ["CM"], 86],
    ["Donadoni", 7, ["RM", "RW"], 86],
    ["Boban", 10, ["AM", "CM"], 86],
    ["Savicevic", 11, ["AM", "LW"], 88],
    ["Massaro", 9, ["ST"], 84],
    ["Panucci", 14, ["RB", "CB"], 82],
  ]),
  club("Atlético Madrid", 2016, "La Liga", [
    ["Oblak", 13, ["GK"], 88],
    ["Juanfran", 20, ["RB"], 84],
    ["Godín", 2, ["CB"], 88],
    ["Giménez", 24, ["CB"], 84],
    ["Filipe Luis", 3, ["LB"], 84],
    ["Gabi", 14, ["DM", "CM"], 84],
    ["Augusto", 5, ["CM"], 82],
    ["Koke", 6, ["CM", "AM"], 85],
    ["Griezmann", 7, ["ST", "AM"], 89],
    ["Torres", 9, ["ST"], 82],
    ["Carrasco", 10, ["LW"], 82],
    ["Saúl", 17, ["CM", "DM"], 82],
  ]),
];

export const CLUB_PLAYERS: Player[] = CLUB_SQUADS.flatMap((s) => s.players);

export function randomClubSquad(excludeIds: string[] = []): Squad {
  const pool = CLUB_SQUADS.filter((s) => !excludeIds.includes(s.id));
  const source = pool.length ? pool : CLUB_SQUADS;
  return source[Math.floor(Math.random() * source.length)]!;
}
