import type { Player, PoolId, Pos, Squad } from "./types";
import { CLUB_PLAYERS, CLUB_SQUADS, randomClubSquad } from "./club-squads";

type Raw = [string, number, Pos[], number];

function squad(nation: string, year: number, rows: Raw[]): Squad {
  const id = `${nation}-${year}`;
  const used = new Set<number>();
  const seen = new Set<string>();
  return {
    id,
    nation,
    year,
    players: rows.map(([name, num, pos, ovr], i) => {
      let n = num;
      while (used.has(n)) n += 1;
      used.add(n);
      let pid = `${id}-${n}-${name}`;
      if (seen.has(pid)) pid = `${pid}-${i}`;
      seen.add(pid);
      return {
        id: pid,
        name,
        nation,
        year,
        num: n,
        pos,
        ovr,
      };
    }),
  };
}

/** OVR is that World Cup or Euros, not a career rating. */
export const SQUADS: Squad[] = [
  squad("Brazil", 1970, [
    ["Félix", 1, ["GK"], 82],
    ["Carlos Alberto", 4, ["RB"], 91],
    ["Britto", 2, ["CB"], 80],
    ["Piazza", 5, ["CB", "DM"], 82],
    ["Everaldo", 6, ["LB"], 80],
    ["Clodoaldo", 8, ["CM", "DM"], 84],
    ["Gérson", 8, ["CM"], 90],
    ["Rivelino", 11, ["LW", "AM", "CM"], 91],
    ["Jairzinho", 7, ["RW", "ST"], 93],
    ["Tostão", 9, ["ST", "AM"], 88],
    ["Pelé", 10, ["ST", "AM"], 97],
    ["Edu", 13, ["LW"], 76],
    ["Paulo Cézar", 15, ["CM", "LW"], 77],
  ]),
  squad("Brazil", 2002, [
    ["Marcos", 1, ["GK"], 84],
    ["Cafu", 2, ["RB"], 88],
    ["Lúcio", 3, ["CB"], 86],
    ["Roque Júnior", 4, ["CB"], 80],
    ["Roberto Carlos", 6, ["LB"], 86],
    ["Gilberto Silva", 5, ["DM"], 86],
    ["Kléberson", 8, ["CM"], 79],
    ["Ronaldinho", 11, ["AM", "LW"], 90],
    ["Rivaldo", 10, ["AM", "LW", "ST"], 90],
    ["Ronaldo", 9, ["ST"], 96],
    ["Edmílson", 5, ["CB", "DM"], 80],
    ["Denílson", 17, ["LW"], 75],
    ["Juninho", 8, ["CM", "AM"], 78],
  ]),
  squad("Argentina", 1986, [
    ["Pumpido", 18, ["GK"], 80],
    ["Ruggeri", 8, ["CB"], 83],
    ["Brown", 6, ["CB"], 82],
    ["Cuciuffo", 9, ["CB"], 78],
    ["Olarticoechea", 13, ["LB", "LM"], 78],
    ["Giusti", 14, ["DM", "CM"], 80],
    ["Batista", 2, ["DM"], 79],
    ["Burruchaga", 7, ["AM", "CM"], 84],
    ["Valdano", 11, ["ST"], 85],
    ["Maradona", 10, ["AM", "ST"], 97],
    ["Enrique", 14, ["CM"], 76],
    ["Borghi", 9, ["ST"], 75],
  ]),
  squad("Argentina", 2022, [
    ["Martínez", 23, ["GK"], 90],
    ["Molina", 26, ["RB"], 83],
    ["Romero", 13, ["CB"], 86],
    ["Otamendi", 19, ["CB"], 82],
    ["Tagliafico", 3, ["LB"], 79],
    ["De Paul", 7, ["CM"], 86],
    ["Fernández", 24, ["CM", "DM"], 85],
    ["Mac Allister", 20, ["CM"], 84],
    ["Di María", 11, ["RW", "AM"], 86],
    ["Messi", 10, ["AM", "RW", "ST"], 97],
    ["Álvarez", 9, ["ST"], 84],
    ["Acuña", 8, ["LB", "LM"], 78],
    ["Paredes", 5, ["DM"], 77],
  ]),
  squad("Germany", 2014, [
    ["Neuer", 1, ["GK"], 93],
    ["Lahm", 16, ["RB", "DM"], 88],
    ["Boateng", 20, ["CB"], 87],
    ["Hummels", 5, ["CB"], 85],
    ["Höwedes", 4, ["CB", "RB"], 80],
    ["Kroos", 18, ["CM", "AM"], 90],
    ["Schweinsteiger", 7, ["CM", "DM"], 86],
    ["Khedira", 6, ["DM", "CM"], 82],
    ["Müller", 13, ["AM", "ST", "RW"], 90],
    ["Klose", 11, ["ST"], 82],
    ["Özil", 8, ["AM"], 82],
    ["Götze", 19, ["AM", "ST"], 81],
    ["Schürrle", 9, ["LW", "ST"], 83],
  ]),
  squad("France", 1998, [
    ["Barthez", 16, ["GK"], 84],
    ["Thuram", 15, ["RB", "CB"], 88],
    ["Blanc", 5, ["CB"], 87],
    ["Desailly", 8, ["CB", "DM"], 84],
    ["Lizarazu", 3, ["LB"], 84],
    ["Deschamps", 7, ["DM"], 83],
    ["Petit", 17, ["CM", "DM"], 82],
    ["Zidane", 10, ["AM"], 94],
    ["Djorkaeff", 6, ["AM", "ST"], 80],
    ["Henry", 12, ["ST", "LW"], 81],
    ["Guivarc'h", 9, ["ST"], 72],
    ["Pires", 11, ["LW", "AM"], 77],
    ["Karembeu", 19, ["CM", "RB"], 79],
  ]),
  squad("France", 2018, [
    ["Lloris", 1, ["GK"], 82],
    ["Pavard", 2, ["RB", "CB"], 82],
    ["Varane", 4, ["CB"], 86],
    ["Umtiti", 5, ["CB"], 83],
    ["Hernández", 21, ["LB"], 82],
    ["Kanté", 13, ["DM", "CM"], 91],
    ["Pogba", 6, ["CM"], 85],
    ["Matuidi", 14, ["CM", "DM"], 81],
    ["Mbappé", 10, ["ST", "RW"], 91],
    ["Griezmann", 7, ["AM", "ST"], 88],
    ["Giroud", 9, ["ST"], 79],
    ["Tolisso", 12, ["CM"], 77],
  ]),
  squad("Spain", 2010, [
    ["Casillas", 1, ["GK"], 90],
    ["Sergio Ramos", 15, ["RB", "CB"], 84],
    ["Piqué", 3, ["CB"], 83],
    ["Puyol", 5, ["CB"], 87],
    ["Capdevila", 11, ["LB"], 79],
    ["Busquets", 16, ["DM"], 86],
    ["Xabi Alonso", 14, ["DM", "CM"], 85],
    ["Xavi", 8, ["CM"], 93],
    ["Iniesta", 6, ["CM", "AM", "LW"], 94],
    ["Pedro", 11, ["RW", "LW"], 80],
    ["Villa", 7, ["ST", "LW"], 91],
    ["Torres", 9, ["ST"], 76],
    ["Silva", 21, ["AM", "RW"], 80],
  ]),
  squad("Italy", 2006, [
    ["Buffon", 1, ["GK"], 93],
    ["Zambrotta", 19, ["RB", "LB"], 85],
    ["Cannavaro", 5, ["CB"], 94],
    ["Nesta", 13, ["CB"], 78],
    ["Grosso", 3, ["LB"], 84],
    ["Pirlo", 21, ["DM", "CM"], 91],
    ["Gattuso", 8, ["DM"], 85],
    ["De Rossi", 4, ["DM", "CM"], 80],
    ["Camoranesi", 16, ["RW", "RM"], 80],
    ["Totti", 10, ["AM", "ST"], 82],
    ["Toni", 9, ["ST"], 78],
    ["Del Piero", 7, ["ST", "AM"], 82],
    ["Perrotta", 20, ["CM"], 79],
  ]),
  squad("England", 1966, [
    ["Banks", 1, ["GK"], 88],
    ["Cohen", 2, ["RB"], 80],
    ["J. Charlton", 5, ["CB"], 83],
    ["Moore", 6, ["CB"], 93],
    ["Wilson", 3, ["LB"], 79],
    ["Stiles", 4, ["DM"], 80],
    ["R. Charlton", 9, ["AM", "CM"], 90],
    ["Peters", 16, ["CM", "AM"], 83],
    ["Ball", 7, ["CM"], 85],
    ["Hunt", 21, ["ST"], 79],
    ["Hurst", 10, ["ST"], 88],
  ]),
  squad("Netherlands", 1974, [
    ["Jongbloed", 8, ["GK"], 78],
    ["Suurbier", 20, ["RB"], 80],
    ["Rijsbergen", 17, ["CB"], 78],
    ["Krol", 12, ["LB", "CB"], 85],
    ["Haan", 7, ["DM", "CM"], 84],
    ["Neeskens", 13, ["CM", "DM"], 90],
    ["van Hanegem", 10, ["CM"], 87],
    ["Rensenbrink", 16, ["LW", "ST"], 86],
    ["Rep", 16, ["RW", "ST"], 84],
    ["Cruyff", 14, ["AM", "ST", "RW"], 96],
    ["Jansen", 6, ["CM"], 76],
  ]),
  squad("Portugal", 2022, [
    ["Costa", 22, ["GK"], 82],
    ["Cancelo", 20, ["RB", "LB"], 83],
    ["Pepe", 3, ["CB"], 82],
    ["Dias", 4, ["CB"], 84],
    ["Guerreiro", 5, ["LB"], 79],
    ["Palhinha", 6, ["DM"], 81],
    ["Bruno Fernandes", 8, ["AM", "CM"], 83],
    ["Bernardo Silva", 10, ["AM", "RW"], 86],
    ["Ronaldo", 7, ["ST"], 78],
    ["João Félix", 11, ["AM", "ST"], 76],
    ["Rafael Leão", 17, ["LW"], 76],
    ["Otávio", 16, ["RW", "AM"], 75],
  ]),
  squad("Croatia", 2018, [
    ["Subašić", 23, ["GK"], 82],
    ["Vrsaljko", 2, ["RB"], 80],
    ["Lovren", 6, ["CB"], 78],
    ["Vida", 21, ["CB"], 78],
    ["Strinić", 3, ["LB"], 76],
    ["Brozović", 11, ["DM", "CM"], 85],
    ["Rakitić", 7, ["CM"], 84],
    ["Modrić", 10, ["CM", "AM"], 94],
    ["Perišić", 4, ["LW", "LM"], 87],
    ["Rebić", 18, ["ST", "LW"], 77],
    ["Mandžukić", 17, ["ST"], 83],
    ["Kramarić", 9, ["ST", "AM"], 77],
  ]),
  squad("Morocco", 2022, [
    ["Bono", 1, ["GK"], 86],
    ["Hakimi", 2, ["RB", "RWB"], 83],
    ["Saïss", 6, ["CB"], 80],
    ["Aguerd", 5, ["CB"], 80],
    ["Mazraoui", 3, ["RB", "LB"], 80],
    ["Amrabat", 4, ["DM"], 88],
    ["Ounahi", 8, ["CM"], 83],
    ["Ziyech", 7, ["RW", "AM"], 82],
    ["Boufal", 17, ["LW", "AM"], 78],
    ["En-Nesyri", 19, ["ST"], 81],
    ["Amallah", 15, ["AM", "CM"], 75],
    ["Dari", 18, ["CB"], 76],
  ]),
  squad("Uruguay", 2010, [
    ["Muslera", 1, ["GK"], 82],
    ["M. Pereira", 16, ["RB"], 78],
    ["Godín", 3, ["CB"], 84],
    ["Lugano", 2, ["CB"], 81],
    ["Cáceres", 4, ["LB", "CB"], 78],
    ["Pérez", 15, ["DM"], 77],
    ["Arevalo", 17, ["DM"], 76],
    ["Diego Forlán", 10, ["ST", "AM"], 92],
    ["Cavani", 7, ["ST"], 78],
    ["Suárez", 9, ["ST"], 84],
    ["Álvaro Pereira", 11, ["LB", "LM"], 77],
  ]),
  squad("Germany", 1990, [
    ["Illgner", 1, ["GK"], 84],
    ["Berthold", 2, ["RB", "CB"], 79],
    ["Kohler", 4, ["CB"], 86],
    ["Augsenthaler", 5, ["CB"], 80],
    ["Brehme", 3, ["LB", "RB"], 86],
    ["Buchwald", 6, ["CB", "DM"], 80],
    ["Häßler", 8, ["AM", "CM"], 82],
    ["Matthäus", 10, ["CM", "DM", "AM"], 92],
    ["Littbarski", 7, ["RW", "AM"], 82],
    ["Klinsmann", 18, ["ST"], 86],
    ["Völler", 9, ["ST"], 84],
  ]),
  squad("Italy", 1982, [
    ["Zoff", 1, ["GK"], 90],
    ["Gentile", 6, ["RB", "CB"], 86],
    ["Scirea", 7, ["CB"], 88],
    ["Collovati", 5, ["CB"], 80],
    ["Cabrini", 3, ["LB"], 81],
    ["Tardelli", 14, ["CM"], 87],
    ["Oriali", 13, ["DM", "CM"], 80],
    ["Antognoni", 10, ["AM"], 78],
    ["Conti", 16, ["RW"], 86],
    ["Rossi", 20, ["ST"], 95],
    ["Graziani", 19, ["ST"], 77],
  ]),
  squad("England", 2018, [
    ["Pickford", 1, ["GK"], 82],
    ["Walker", 2, ["RB", "CB"], 81],
    ["Stones", 5, ["CB"], 82],
    ["Maguire", 6, ["CB"], 82],
    ["Young", 3, ["LB", "LM"], 77],
    ["Henderson", 8, ["CM", "DM"], 79],
    ["Alli", 10, ["AM", "CM"], 77],
    ["Lingard", 7, ["AM", "RW"], 78],
    ["Sterling", 10, ["LW", "ST"], 81],
    ["Kane", 9, ["ST"], 86],
    ["Rashford", 11, ["LW", "ST"], 78],
    ["Trippier", 12, ["RB"], 82],
  ]),
  squad("Belgium", 2018, [
    ["Courtois", 1, ["GK"], 90],
    ["Meunier", 15, ["RB"], 78],
    ["Alderweireld", 2, ["CB"], 82],
    ["Kompany", 4, ["CB"], 80],
    ["Vertonghen", 5, ["CB", "LB"], 81],
    ["Witsel", 6, ["DM"], 80],
    ["De Bruyne", 7, ["AM", "CM"], 85],
    ["Hazard", 10, ["LW", "AM"], 88],
    ["Mertens", 14, ["ST", "RW"], 79],
    ["Lukaku", 9, ["ST"], 82],
    ["Carrasco", 11, ["LW"], 77],
    ["Fellaini", 8, ["CM"], 76],
  ]),
  squad("Spain", 2022, [
    ["Simón", 23, ["GK"], 80],
    ["Carvajal", 2, ["RB"], 79],
    ["Rodri", 16, ["DM", "CB"], 83],
    ["Laporte", 14, ["CB"], 81],
    ["Alba", 18, ["LB"], 78],
    ["Busquets", 5, ["DM"], 81],
    ["Pedri", 26, ["CM", "AM"], 85],
    ["Gavi", 9, ["CM"], 79],
    ["Olmo", 21, ["AM", "LW"], 80],
    ["Morata", 7, ["ST"], 77],
    ["Williams", 12, ["RW", "ST"], 78],
    ["Asensio", 10, ["RW", "AM"], 76],
  ]),
  squad("Colombia", 2014, [
    ["Ospina", 1, ["GK"], 82],
    ["Zúñiga", 18, ["RB"], 78],
    ["Yepes", 2, ["CB"], 79],
    ["Zapata", 3, ["CB"], 80],
    ["Armero", 7, ["LB"], 77],
    ["Sánchez", 6, ["DM", "CM"], 79],
    ["Guarín", 13, ["CM"], 78],
    ["Rodríguez", 10, ["AM", "CM"], 92],
    ["Cuadrado", 11, ["RW"], 82],
    ["Gutiérrez", 19, ["ST", "AM"], 77],
    ["Martínez", 21, ["ST"], 80],
    ["Ramos", 9, ["ST"], 75],
  ]),
  squad("Japan", 2022, [
    ["Gonda", 12, ["GK"], 76],
    ["Yamane", 2, ["RB"], 77],
    ["Yoshida", 22, ["CB"], 80],
    ["Itakura", 4, ["CB"], 80],
    ["Nagatomo", 5, ["LB"], 76],
    ["Endo", 6, ["DM"], 83],
    ["Tanaka", 17, ["CM"], 81],
    ["Kamada", 15, ["AM"], 80],
    ["Ito", 14, ["RW"], 80],
    ["Doan", 8, ["RW", "AM"], 82],
    ["Maeda", 25, ["ST"], 78],
    ["Mitoma", 9, ["LW"], 80],
  ]),
  squad("USA", 2022, [
    ["Turner", 1, ["GK"], 81],
    ["Dest", 2, ["RB", "LB"], 78],
    ["Zimmerman", 3, ["CB"], 79],
    ["Ream", 13, ["CB"], 78],
    ["Robinson", 5, ["LB"], 80],
    ["Adams", 4, ["DM"], 83],
    ["McKennie", 8, ["CM"], 81],
    ["Musah", 6, ["CM"], 80],
    ["Weah", 21, ["RW", "ST"], 80],
    ["Pulisic", 10, ["LW", "AM"], 83],
    ["Sargent", 24, ["ST"], 75],
    ["Reyna", 7, ["AM"], 77],
  ]),
  squad("Brazil", 1994, [
    ["Taffarel", 1, ["GK"], 86],
    ["Jorginho", 2, ["RB"], 80],
    ["Aldair", 3, ["CB"], 85],
    ["Márcio Santos", 15, ["CB"], 79],
    ["Branco", 6, ["LB"], 80],
    ["Dunga", 8, ["DM"], 86],
    ["Mauro Silva", 5, ["DM"], 84],
    ["Mazinho", 16, ["CM"], 79],
    ["Zinho", 9, ["AM", "CM"], 80],
    ["Romário", 11, ["ST"], 95],
    ["Bebeto", 7, ["ST"], 88],
    ["Rai", 10, ["AM"], 78],
  ]),
  squad("France", 2022, [
    ["Lloris", 1, ["GK"], 80],
    ["Pavard", 2, ["RB"], 78],
    ["Varane", 4, ["CB"], 83],
    ["Upamecano", 18, ["CB"], 78],
    ["T. Hernández", 22, ["LB"], 82],
    ["Tchouaméni", 8, ["DM"], 80],
    ["Rabiot", 14, ["CM"], 81],
    ["Griezmann", 7, ["AM", "ST"], 85],
    ["Dembélé", 11, ["RW"], 82],
    ["Mbappé", 10, ["ST", "LW"], 94],
    ["Giroud", 9, ["ST"], 83],
    ["Camavinga", 6, ["CM", "LB"], 78],
  ]),
  squad("Brazil", 1958, [
    ["Gilmar", 3, ["GK"], 84],
    ["Djalma Santos", 4, ["RB"], 86],
    ["Bellini", 2, ["CB"], 81],
    ["Orlando", 5, ["CB"], 79],
    ["Nílton Santos", 6, ["LB"], 88],
    ["Zito", 8, ["CM", "DM"], 82],
    ["Didi", 10, ["CM", "AM"], 92],
    ["Garrincha", 7, ["RW"], 93],
    ["Vavá", 9, ["ST"], 86],
    ["Pelé", 10, ["ST", "AM"], 94],
    ["Zagallo", 11, ["LW"], 84],
  ]),
  squad("Argentina", 1978, [
    ["Fillol", 5, ["GK"], 87],
    ["Olguín", 15, ["RB"], 79],
    ["Passarella", 7, ["CB"], 87],
    ["Galván", 8, ["CB"], 79],
    ["Tarantini", 20, ["LB"], 80],
    ["Ardiles", 2, ["CM"], 83],
    ["Gallego", 6, ["DM"], 79],
    ["Kempes", 10, ["ST", "AM"], 94],
    ["Bertoni", 4, ["RW"], 83],
    ["Luque", 14, ["ST"], 81],
    ["Ortiz", 16, ["LW"], 76],
  ]),
  squad("Netherlands", 2010, [
    ["Stekelenburg", 1, ["GK"], 82],
    ["Van der Wiel", 2, ["RB"], 77],
    ["Heitinga", 3, ["CB"], 78],
    ["Mathijsen", 4, ["CB"], 79],
    ["Van Bronckhorst", 5, ["LB"], 82],
    ["Van Bommel", 6, ["DM"], 80],
    ["Sneijder", 10, ["AM", "CM"], 91],
    ["Kuyt", 7, ["RW", "ST"], 79],
    ["Robben", 11, ["RW"], 86],
    ["Van Persie", 9, ["ST"], 82],
    ["Afellay", 8, ["AM", "LW"], 76],
  ]),
  squad("Senegal", 2002, [
    ["Sylva", 1, ["GK"], 80],
    ["Daf", 2, ["RB"], 78],
    ["Coly", 4, ["CB"], 76],
    ["Diawara", 13, ["CB"], 76],
    ["Diao", 6, ["DM", "CM"], 77],
    ["Cissé", 10, ["CM"], 76],
    ["Fadiga", 11, ["AM", "LW"], 80],
    ["Diouf", 9, ["ST", "RW"], 84],
    ["Camara", 7, ["ST"], 77],
    ["H. Camara", 12, ["LW", "ST"], 82],
    ["N'Diaye", 15, ["CB"], 74],
  ]),
  squad("Argentina", 2014, [
    ["Romero", 1, ["GK"], 84],
    ["Zabaleta", 4, ["RB"], 80],
    ["Garay", 2, ["CB"], 83],
    ["Demichelis", 6, ["CB"], 78],
    ["Rojo", 16, ["LB", "CB"], 79],
    ["Mascherano", 14, ["DM"], 87],
    ["Biglia", 19, ["CM"], 77],
    ["Di María", 7, ["RW", "AM"], 82],
    ["Messi", 10, ["AM", "RW", "ST"], 88],
    ["Higuaín", 9, ["ST"], 78],
    ["Agüero", 11, ["ST"], 79],
    ["Lavezzi", 22, ["LW", "ST"], 77],
  ]),
  squad("Brazil", 1982, [
    ["Valdir Peres", 1, ["GK"], 74],
    ["Leandro", 2, ["RB"], 82],
    ["Oscar", 3, ["CB"], 80],
    ["Luizinho", 4, ["CB"], 79],
    ["Júnior", 6, ["LB"], 86],
    ["Cerezo", 5, ["CM", "DM"], 82],
    ["Falcão", 15, ["CM"], 92],
    ["Sócrates", 8, ["AM", "CM"], 91],
    ["Zico", 10, ["AM", "ST"], 90],
    ["Éder", 9, ["ST", "LW"], 83],
    ["Serginho", 11, ["ST"], 74],
    ["Paulo Isidoro", 16, ["CM", "RW"], 76],
  ]),
  squad("Germany", 2002, [
    ["Kahn", 1, ["GK"], 93],
    ["Frings", 22, ["RB", "CM"], 78],
    ["Linke", 2, ["CB"], 77],
    ["Metzelder", 21, ["CB"], 79],
    ["Bode", 17, ["LB"], 76],
    ["Hamann", 6, ["DM"], 81],
    ["Schneider", 19, ["CM", "AM"], 78],
    ["Ballack", 13, ["CM", "AM"], 88],
    ["Klose", 11, ["ST"], 88],
    ["Neuville", 7, ["AM", "RW"], 79],
    ["Jancker", 9, ["ST"], 75],
    ["Ramlow", 8, ["CM"], 72],
  ]),
  squad("Italy", 1994, [
    ["Pagliuca", 1, ["GK"], 78],
    ["Mussi", 2, ["RB"], 76],
    ["Baresi", 6, ["CB"], 88],
    ["Maldini", 3, ["LB", "CB"], 87],
    ["Costacurta", 5, ["CB"], 83],
    ["Albertini", 4, ["CM"], 82],
    ["Donadoni", 17, ["RM", "RW"], 81],
    ["Baggio", 10, ["AM", "ST"], 93],
    ["Signori", 18, ["ST", "LW"], 78],
    ["Massaro", 19, ["ST"], 77],
    ["Casiraghi", 20, ["ST"], 75],
    ["Evani", 11, ["AM"], 75],
  ]),
  squad("Netherlands", 1988, [
    ["Van Breukelen", 1, ["GK"], 84],
    ["Van Aerle", 2, ["RB"], 78],
    ["R. Koeman", 4, ["CB"], 84],
    ["Rijkaard", 8, ["CB", "DM"], 87],
    ["Van Tiggelen", 5, ["LB"], 79],
    ["Wouters", 6, ["CM"], 80],
    ["Mühren", 10, ["AM", "CM"], 81],
    ["Gullit", 7, ["AM", "ST"], 90],
    ["Van Basten", 9, ["ST"], 95],
    ["Kieft", 14, ["ST"], 76],
    ["Vanenburg", 11, ["RW"], 80],
  ]),
  squad("England", 2022, [
    ["Pickford", 1, ["GK"], 82],
    ["Walker", 2, ["RB"], 80],
    ["Stones", 5, ["CB"], 82],
    ["Maguire", 6, ["CB"], 75],
    ["Trippier", 12, ["RB", "LB"], 79],
    ["Rice", 4, ["DM"], 84],
    ["Bellingham", 22, ["CM", "AM"], 84],
    ["Mount", 19, ["AM"], 77],
    ["Saka", 17, ["RW"], 83],
    ["Kane", 9, ["ST"], 82],
    ["Sterling", 10, ["LW"], 78],
    ["Foden", 20, ["AM", "LW"], 79],
  ]),
  squad("Portugal", 2016, [
    ["Rui Patrício", 1, ["GK"], 82],
    ["Cédric", 21, ["RB"], 77],
    ["Pepe", 3, ["CB"], 85],
    ["Fonte", 4, ["CB"], 80],
    ["Guerreiro", 5, ["LB"], 77],
    ["William Carvalho", 14, ["DM"], 79],
    ["Moutinho", 8, ["CM"], 80],
    ["João Mário", 10, ["AM", "CM"], 77],
    ["Ronaldo", 7, ["ST"], 86],
    ["Nani", 17, ["RW", "LW"], 80],
    ["Quaresma", 20, ["RW"], 78],
    ["Sanches", 16, ["CM"], 82],
  ]),
  squad("France", 2006, [
    ["Barthez", 16, ["GK"], 80],
    ["Sagnol", 19, ["RB"], 80],
    ["Thuram", 15, ["CB", "RB"], 83],
    ["Gallas", 5, ["CB"], 80],
    ["Abidal", 3, ["LB"], 79],
    ["Vieira", 4, ["DM", "CM"], 83],
    ["Makélélé", 6, ["DM"], 85],
    ["Zidane", 10, ["AM"], 92],
    ["Ribéry", 22, ["LW"], 81],
    ["Henry", 12, ["ST"], 84],
    ["Trezeguet", 9, ["ST"], 78],
    ["Malouda", 11, ["LW", "AM"], 77],
  ]),
  squad("Spain", 2008, [
    ["Casillas", 1, ["GK"], 88],
    ["Sergio Ramos", 15, ["RB"], 82],
    ["Puyol", 5, ["CB"], 84],
    ["Marchena", 4, ["CB"], 78],
    ["Capdevila", 11, ["LB"], 78],
    ["Senna", 19, ["DM"], 85],
    ["Xavi", 8, ["CM"], 93],
    ["Iniesta", 6, ["AM", "CM"], 90],
    ["Silva", 21, ["AM", "RW"], 82],
    ["Villa", 7, ["ST", "LW"], 90],
    ["Torres", 9, ["ST"], 88],
    ["Fàbregas", 10, ["AM", "CM"], 84],
  ]),
  squad("Croatia", 2022, [
    ["Livaković", 1, ["GK"], 88],
    ["Juranović", 22, ["RB"], 78],
    ["Lovren", 6, ["CB"], 77],
    ["Gvardiol", 20, ["CB", "LB"], 86],
    ["Sosa", 19, ["LB"], 76],
    ["Modrić", 10, ["CM", "AM"], 87],
    ["Brozović", 11, ["DM"], 85],
    ["Kovačić", 8, ["CM"], 82],
    ["Perišić", 4, ["LW", "LM"], 83],
    ["Kramarić", 9, ["ST", "AM"], 80],
    ["Livaja", 14, ["ST"], 75],
    ["Pašalić", 15, ["CM", "AM"], 77],
  ]),
  squad("Mexico", 1986, [
    ["Larios", 1, ["GK"], 78],
    ["Trejo", 18, ["RB"], 74],
    ["Quirarte", 2, ["CB"], 78],
    ["Servín", 3, ["CB"], 76],
    ["Amador", 14, ["LB"], 75],
    ["España", 6, ["DM"], 78],
    ["Aguirre", 7, ["CM"], 80],
    ["Negrete", 8, ["AM", "CM"], 84],
    ["Boy", 10, ["AM", "LW"], 80],
    ["Sánchez", 9, ["ST"], 86],
    ["Flores", 11, ["ST", "RW"], 77],
    ["Muñoz", 21, ["ST"], 74],
  ]),
  squad("Denmark", 1992, [
    ["Schmeichel", 1, ["GK"], 90],
    ["Sivebæk", 2, ["RB"], 76],
    ["Olsen", 4, ["CB"], 79],
    ["L. Olsen", 3, ["CB"], 78],
    ["Christofte", 5, ["LB"], 80],
    ["Jensen", 6, ["CM"], 80],
    ["Vilfort", 18, ["CM"], 82],
    ["B. Laudrup", 11, ["LW", "AM"], 82],
    ["M. Laudrup", 10, ["AM", "RW"], 90],
    ["Povlsen", 9, ["ST"], 78],
    ["Elstrup", 17, ["ST"], 75],
    ["Larsen", 7, ["RW"], 79],
  ]),
  squad("Switzerland", 2022, [
    ["Sommer", 1, ["GK"], 85],
    ["Widmer", 3, ["RB"], 77],
    ["Akanji", 5, ["CB"], 81],
    ["Elvedi", 4, ["CB"], 78],
    ["Rodríguez", 13, ["LB"], 76],
    ["Xhaka", 10, ["CM", "DM"], 82],
    ["Freuler", 8, ["CM"], 79],
    ["Shaqiri", 23, ["RW", "AM"], 80],
    ["Embolo", 7, ["ST"], 79],
    ["Seferovic", 9, ["ST"], 74],
    ["Vargas", 17, ["LW"], 75],
    ["Sow", 15, ["DM"], 76],
  ]),
  squad("Poland", 1982, [
    ["Młynarczyk", 1, ["GK"], 82],
    ["Jalocha", 2, ["RB"], 76],
    ["Żmuda", 6, ["CB"], 80],
    ["Majewski", 4, ["CB"], 76],
    ["Kupcewicz", 3, ["LB", "LM"], 76],
    ["Buncol", 5, ["CM"], 77],
    ["Matysik", 8, ["DM"], 76],
    ["Boniek", 20, ["AM", "CM"], 88],
    ["Lato", 16, ["RW", "ST"], 82],
    ["Smolarek", 11, ["ST", "LW"], 81],
    ["Ciołek", 17, ["ST"], 74],
    ["Dziekanowski", 19, ["ST"], 75],
  ]),
  squad("Sweden", 1994, [
    ["Ravelli", 1, ["GK"], 85],
    ["R. Nilsson", 2, ["RB"], 78],
    ["Björklund", 4, ["CB"], 78],
    ["P. Andersson", 5, ["CB"], 78],
    ["Schwarz", 3, ["LB"], 76],
    ["Thern", 8, ["CM"], 81],
    ["Ingesson", 6, ["CM", "DM"], 78],
    ["Brolin", 10, ["AM", "ST"], 86],
    ["Dahlin", 11, ["ST"], 80],
    ["K. Andersson", 19, ["ST"], 84],
    ["Larsson", 7, ["RW"], 77],
    ["Mild", 9, ["CM"], 75],
  ]),
  squad("Nigeria", 1998, [
    ["Rufai", 1, ["GK"], 80],
    ["Babayaro", 3, ["LB"], 77],
    ["West", 5, ["CB"], 76],
    ["Okechukwu", 6, ["CB"], 78],
    ["Taribo", 4, ["CB", "DM"], 78],
    ["Okocha", 10, ["AM", "RW"], 86],
    ["Oliseh", 8, ["CM", "DM"], 80],
    ["Lawal", 15, ["CM"], 76],
    ["Kanu", 9, ["ST", "AM"], 83],
    ["Ikpeba", 11, ["ST"], 79],
    ["Amokachi", 7, ["ST"], 77],
    ["Finidi", 14, ["RW"], 80],
  ]),
  squad("Ghana", 2010, [
    ["Kingson", 22, ["GK"], 77],
    ["Pantsil", 2, ["RB"], 76],
    ["Mensah", 4, ["CB"], 78],
    ["Vorsah", 5, ["CB"], 75],
    ["Sarpei", 3, ["LB"], 75],
    ["Annan", 6, ["DM"], 80],
    ["Essien", 8, ["CM", "DM"], 78],
    ["Muntari", 11, ["CM"], 77],
    ["Gyan", 3, ["ST"], 83],
    ["Asamoah", 7, ["LW", "CM"], 80],
    ["A. Ayew", 10, ["ST", "LW"], 77],
    ["Tagoe", 18, ["RW"], 73],
  ]),
  squad("Cameroon", 1990, [
    ["N'Kono", 1, ["GK"], 85],
    ["Kundé", 6, ["RB", "CB"], 78],
    ["Tataw", 4, ["CB"], 78],
    ["Massing", 5, ["CB"], 76],
    ["Kana-Biyik", 14, ["CB", "DM"], 76],
    ["M'Bouh", 8, ["DM"], 75],
    ["Mfede", 10, ["CM", "AM"], 75],
    ["Pagal", 15, ["CM"], 74],
    ["Milla", 9, ["ST"], 90],
    ["Omam-Biyik", 7, ["ST"], 82],
    ["Makanaky", 11, ["RW", "AM"], 76],
    ["Ebwelle", 17, ["LW"], 73],
  ]),
  squad("Korea", 2002, [
    ["Lee Woon-jae", 1, ["GK"], 84],
    ["Song Chong-gug", 22, ["RB"], 77],
    ["Choi Jin-cheul", 4, ["CB"], 76],
    ["Hong Myung-bo", 20, ["CB", "DM"], 85],
    ["Kim Tae-young", 5, ["CB"], 76],
    ["Kim Nam-il", 6, ["DM"], 75],
    ["Yoo Sang-chul", 10, ["CM"], 78],
    ["Park Ji-sung", 21, ["CM", "RW"], 82],
    ["Seol Ki-hyeon", 11, ["RW", "ST"], 78],
    ["Ahn Jung-hwan", 9, ["ST"], 84],
    ["Hwang Sun-hong", 18, ["ST"], 78],
    ["Lee Young-pyo", 14, ["LB"], 79],
  ]),
  squad("Australia", 2006, [
    ["Schwarzer", 1, ["GK"], 82],
    ["Neill", 2, ["RB", "CB"], 79],
    ["Moore", 5, ["CB"], 76],
    ["Popovic", 6, ["CB"], 76],
    ["Chipperfield", 3, ["LB", "LM"], 76],
    ["Grella", 8, ["DM"], 76],
    ["Culina", 4, ["CM"], 78],
    ["Bresciano", 10, ["AM"], 79],
    ["Kewell", 7, ["LW", "AM"], 80],
    ["Viduka", 9, ["ST"], 82],
    ["Cahill", 11, ["ST", "AM"], 83],
    ["Emerton", 14, ["RW"], 77],
  ]),
  squad("Ecuador", 2006, [
    ["Cevallos", 1, ["GK"], 78],
    ["De la Cruz", 2, ["RB"], 76],
    ["Hurtado", 3, ["CB"], 78],
    ["Espinoza", 4, ["CB"], 76],
    ["Reasco", 18, ["LB"], 75],
    ["Castillo", 6, ["DM"], 76],
    ["Valencia", 8, ["CM"], 77],
    ["Méndez", 16, ["CM", "AM"], 79],
    ["Delgado", 11, ["AM", "LW"], 83],
    ["Tenorio", 9, ["ST"], 81],
    ["Kaviedes", 21, ["ST"], 77],
    ["Lara", 7, ["RW"], 73],
  ]),
  squad("Chile", 2014, [
    ["Bravo", 1, ["GK"], 85],
    ["Silva", 4, ["RB"], 76],
    ["Medel", 17, ["CB", "DM"], 81],
    ["Jara", 18, ["CB"], 78],
    ["Mena", 2, ["LB"], 76],
    ["Díaz", 8, ["DM"], 78],
    ["Aránguiz", 20, ["CM"], 80],
    ["Vidal", 10, ["CM", "AM"], 85],
    ["Valdivia", 10, ["AM"], 79],
    ["Sánchez", 7, ["LW", "ST"], 83],
    ["Vargas", 11, ["RW", "ST"], 80],
    ["Beausejour", 15, ["LB", "LM"], 76],
  ]),
  squad("Serbia", 2018, [
    ["Rajković", 1, ["GK"], 76],
    ["Rukavina", 2, ["RB"], 74],
    ["Milenković", 15, ["CB"], 78],
    ["Maksimović", 6, ["CB"], 76],
    ["Kolarov", 11, ["LB"], 79],
    ["Matić", 21, ["DM"], 80],
    ["Milivojević", 4, ["CM"], 76],
    ["Tadić", 10, ["AM", "LW"], 82],
    ["Kostić", 17, ["LW"], 80],
    ["Mitrović", 9, ["ST"], 81],
    ["Ljajić", 22, ["AM", "RW"], 76],
    ["Milinković-Savić", 20, ["CM", "AM"], 78],
  ]),
  squad("Turkey", 2002, [
    ["Rüştü", 1, ["GK"], 87],
    ["Fatih", 4, ["RB"], 76],
    ["Alpay", 3, ["CB"], 79],
    ["Bülent", 5, ["CB"], 78],
    ["Ergün", 16, ["LB", "CM"], 76],
    ["Tugay", 8, ["CM", "DM"], 81],
    ["Emre", 5, ["CM"], 80],
    ["Davala", 22, ["RW", "RB"], 80],
    ["Baştürk", 10, ["AM"], 79],
    ["Hakan Şükür", 9, ["ST"], 84],
    ["Nihat", 11, ["ST"], 83],
    ["Buruk", 21, ["CM"], 76],
  ]),
];

export const ALL_PLAYERS: Player[] = SQUADS.flatMap((s) => s.players);

export function playersForSide(label: string, pool: PoolId = "world"): Player[] {
  const list = pool === "club" ? CLUB_PLAYERS : ALL_PLAYERS;
  const raw = label.replace(/\s+(19|20)\d{2}$/, "").trim().toLowerCase();
  const aliases: Record<string, string> = {
    united: "manchester united",
    city: "manchester city",
    bayern: "bayern munich",
    milan: "ac milan",
    dortmund: "borussia dortmund",
    atlético: "atlético madrid",
    atletico: "atlético madrid",
    leverkusen: "bayer leverkusen",
  };
  const key = aliases[raw] ?? raw;
  return list.filter((player) => player.nation.toLowerCase() === key);
}

export function randomSquad(excludeIds: string[] = [], pool: PoolId = "world"): Squad {
  if (pool === "club") return randomClubSquad(excludeIds);
  const filtered = SQUADS.filter((s) => !excludeIds.includes(s.id));
  const source = filtered.length ? filtered : SQUADS;
  return source[Math.floor(Math.random() * source.length)]!;
}

export function otherYears(squad: Squad, excludeIds: string[] = [], pool: PoolId = "world"): Squad[] {
  const list = pool === "club" ? CLUB_SQUADS : SQUADS;
  return list.filter(
    (s) => s.nation === squad.nation && s.id !== squad.id && !excludeIds.includes(s.id),
  );
}

export { CLUB_SQUADS };
