import type { Player, PoolId, Pos, Squad } from "./types";
import { CLUB_SQUADS, randomClubSquad } from "./club-squads";

type Raw = [string, number, Pos[], number];

function squad(nation: string, year: number, rows: Raw[]): Squad {
  const id = `${nation}-${year}`;
  const used = new Set<number>();
  const seen = new Set<string>();
  return {
    id,
    nation,
    year,
    players: rows.map(([name, num, pos, ovr], i) => {
      let n = num;
      while (used.has(n)) n += 1;
      used.add(n);
      let pid = `${id}-${n}-${name}`;
      if (seen.has(pid)) pid = `${pid}-${i}`;
      seen.add(pid);
      return {
        id: pid,
        name,
        nation,
        year,
        num: n,
        pos,
        ovr,
      };
    }),
  };
}

export const SQUADS: Squad[] = [
  squad("Brazil", 1970, [
    ["Félix", 1, ["GK"], 86],
    ["Carlos Alberto", 4, ["RB"], 94],
    ["Britto", 2, ["CB"], 84],
    ["Piazza", 5, ["CB", "DM"], 86],
    ["Everaldo", 6, ["LB"], 85],
    ["Clodoaldo", 8, ["CM", "DM"], 88],
    ["Gérson", 8, ["CM"], 93],
    ["Rivelino", 11, ["LW", "AM", "CM"], 93],
    ["Jairzinho", 7, ["RW", "ST"], 94],
    ["Tostão", 9, ["ST", "AM"], 91],
    ["Pelé", 10, ["ST", "AM"], 99],
    ["Edu", 13, ["LW"], 84],
    ["Paulo Cézar", 15, ["CM", "LW"], 85],
  ]),
  squad("Brazil", 2002, [
    ["Marcos", 1, ["GK"], 88],
    ["Cafu", 2, ["RB"], 94],
    ["Lúcio", 3, ["CB"], 90],
    ["Roque Júnior", 4, ["CB"], 84],
    ["Roberto Carlos", 6, ["LB"], 94],
    ["Gilberto Silva", 5, ["DM"], 89],
    ["Kléberson", 8, ["CM"], 84],
    ["Ronaldinho", 11, ["AM", "LW"], 95],
    ["Rivaldo", 10, ["AM", "LW", "ST"], 94],
    ["Ronaldo", 9, ["ST"], 97],
    ["Edmílson", 5, ["CB", "DM"], 86],
    ["Denílson", 17, ["LW"], 83],
    ["Juninho", 8, ["CM", "AM"], 86],
  ]),
  squad("Argentina", 1986, [
    ["Pumpido", 18, ["GK"], 86],
    ["Ruggeri", 8, ["CB"], 88],
    ["Brown", 6, ["CB"], 85],
    ["Cuciuffo", 9, ["CB"], 82],
    ["Olarticoechea", 13, ["LB", "LM"], 84],
    ["Giusti", 14, ["DM", "CM"], 85],
    ["Batista", 2, ["DM"], 84],
    ["Burruchaga", 7, ["AM", "CM"], 88],
    ["Valdano", 11, ["ST"], 88],
    ["Maradona", 10, ["AM", "ST"], 99],
    ["Enrique", 14, ["CM"], 82],
    ["Borghi", 9, ["ST"], 83],
  ]),
  squad("Argentina", 2022, [
    ["Martínez", 23, ["GK"], 91],
    ["Molina", 26, ["RB"], 86],
    ["Romero", 13, ["CB"], 88],
    ["Otamendi", 19, ["CB"], 85],
    ["Tagliafico", 3, ["LB"], 84],
    ["De Paul", 7, ["CM"], 88],
    ["Fernández", 24, ["CM", "DM"], 88],
    ["Mac Allister", 20, ["CM"], 87],
    ["Di María", 11, ["RW", "AM"], 90],
    ["Messi", 10, ["AM", "RW", "ST"], 98],
    ["Álvarez", 9, ["ST"], 88],
    ["Acuña", 8, ["LB", "LM"], 84],
    ["Paredes", 5, ["DM"], 84],
  ]),
  squad("Germany", 2014, [
    ["Neuer", 1, ["GK"], 94],
    ["Lahm", 16, ["RB", "DM"], 92],
    ["Boateng", 20, ["CB"], 90],
    ["Hummels", 5, ["CB"], 89],
    ["Höwedes", 4, ["CB", "RB"], 84],
    ["Kroos", 18, ["CM", "AM"], 92],
    ["Schweinsteiger", 7, ["CM", "DM"], 90],
    ["Khedira", 6, ["DM", "CM"], 86],
    ["Müller", 13, ["AM", "ST", "RW"], 92],
    ["Klose", 11, ["ST"], 86],
    ["Özil", 8, ["AM"], 89],
    ["Götze", 19, ["AM", "ST"], 87],
    ["Schürrle", 9, ["LW", "ST"], 84],
  ]),
  squad("France", 1998, [
    ["Barthez", 16, ["GK"], 89],
    ["Thuram", 15, ["RB", "CB"], 91],
    ["Blanc", 5, ["CB"], 90],
    ["Desailly", 8, ["CB", "DM"], 91],
    ["Lizarazu", 3, ["LB"], 88],
    ["Deschamps", 7, ["DM"], 89],
    ["Petit", 17, ["CM", "DM"], 88],
    ["Zidane", 10, ["AM"], 96],
    ["Djorkaeff", 6, ["AM", "ST"], 86],
    ["Henry", 12, ["ST", "LW"], 90],
    ["Guivarc'h", 9, ["ST"], 78],
    ["Pires", 11, ["LW", "AM"], 85],
    ["Karembeu", 19, ["CM", "RB"], 84],
  ]),
  squad("France", 2018, [
    ["Lloris", 1, ["GK"], 88],
    ["Pavard", 2, ["RB", "CB"], 84],
    ["Varane", 4, ["CB"], 90],
    ["Umtiti", 5, ["CB"], 86],
    ["Hernández", 21, ["LB"], 86],
    ["Kanté", 13, ["DM", "CM"], 91],
    ["Pogba", 6, ["CM"], 88],
    ["Matuidi", 14, ["CM", "DM"], 85],
    ["Mbappé", 10, ["ST", "RW"], 94],
    ["Griezmann", 7, ["AM", "ST"], 90],
    ["Giroud", 9, ["ST"], 84],
    ["Tolisso", 12, ["CM"], 83],
  ]),
  squad("Spain", 2010, [
    ["Casillas", 1, ["GK"], 92],
    ["Sergio Ramos", 15, ["RB", "CB"], 90],
    ["Piqué", 3, ["CB"], 89],
    ["Puyol", 5, ["CB"], 90],
    ["Capdevila", 11, ["LB"], 84],
    ["Busquets", 16, ["DM"], 90],
    ["Xabi Alonso", 14, ["DM", "CM"], 89],
    ["Xavi", 8, ["CM"], 95],
    ["Iniesta", 6, ["CM", "AM", "LW"], 94],
    ["Pedro", 11, ["RW", "LW"], 86],
    ["Villa", 7, ["ST", "LW"], 91],
    ["Torres", 9, ["ST"], 86],
    ["Silva", 21, ["AM", "RW"], 88],
  ]),
  squad("Italy", 2006, [
    ["Buffon", 1, ["GK"], 94],
    ["Zambrotta", 19, ["RB", "LB"], 88],
    ["Cannavaro", 5, ["CB"], 93],
    ["Nesta", 13, ["CB"], 92],
    ["Grosso", 3, ["LB"], 84],
    ["Pirlo", 21, ["DM", "CM"], 93],
    ["Gattuso", 8, ["DM"], 87],
    ["De Rossi", 4, ["DM", "CM"], 86],
    ["Camoranesi", 16, ["RW", "RM"], 84],
    ["Totti", 10, ["AM", "ST"], 91],
    ["Toni", 9, ["ST"], 86],
    ["Del Piero", 7, ["ST", "AM"], 88],
    ["Perrotta", 20, ["CM"], 83],
  ]),
  squad("England", 1966, [
    ["Banks", 1, ["GK"], 92],
    ["Cohen", 2, ["RB"], 84],
    ["J. Charlton", 5, ["CB"], 88],
    ["Moore", 6, ["CB"], 94],
    ["Wilson", 3, ["LB"], 83],
    ["Stiles", 4, ["DM"], 84],
    ["R. Charlton", 9, ["AM", "CM"], 93],
    ["Peters", 16, ["CM", "AM"], 86],
    ["Ball", 7, ["CM"], 85],
    ["Hunt", 21, ["ST"], 84],
    ["Hurst", 10, ["ST"], 88],
  ]),
  squad("Netherlands", 1974, [
    ["Jongbloed", 8, ["GK"], 82],
    ["Suurbier", 20, ["RB"], 84],
    ["Rijsbergen", 17, ["CB"], 84],
    ["Krol", 12, ["LB", "CB"], 90],
    ["Haan", 7, ["DM", "CM"], 86],
    ["Neeskens", 13, ["CM", "DM"], 92],
    ["van Hanegem", 10, ["CM"], 90],
    ["Rensenbrink", 16, ["LW", "ST"], 91],
    ["Rep", 16, ["RW", "ST"], 86],
    ["Cruyff", 14, ["AM", "ST", "RW"], 98],
    ["Jansen", 6, ["CM"], 83],
  ]),
  squad("Portugal", 2022, [
    ["Costa", 22, ["GK"], 86],
    ["Cancelo", 20, ["RB", "LB"], 88],
    ["Pepe", 3, ["CB"], 86],
    ["Dias", 4, ["CB"], 89],
    ["Guerreiro", 5, ["LB"], 84],
    ["Palhinha", 6, ["DM"], 85],
    ["Bruno Fernandes", 8, ["AM", "CM"], 88],
    ["Bernardo Silva", 10, ["AM", "RW"], 90],
    ["Ronaldo", 7, ["ST"], 90],
    ["João Félix", 11, ["AM", "ST"], 84],
    ["Rafael Leão", 17, ["LW"], 86],
    ["Otávio", 16, ["RW", "AM"], 83],
  ]),
  squad("Croatia", 2018, [
    ["Subašić", 23, ["GK"], 84],
    ["Vrsaljko", 2, ["RB"], 82],
    ["Lovren", 6, ["CB"], 84],
    ["Vida", 21, ["CB"], 82],
    ["Strinić", 3, ["LB"], 80],
    ["Brozović", 11, ["DM", "CM"], 86],
    ["Rakitić", 7, ["CM"], 88],
    ["Modrić", 10, ["CM", "AM"], 94],
    ["Perišić", 4, ["LW", "LM"], 87],
    ["Rebić", 18, ["ST", "LW"], 83],
    ["Mandžukić", 17, ["ST"], 85],
    ["Kramarić", 9, ["ST", "AM"], 84],
  ]),
  squad("Morocco", 2022, [
    ["Bono", 1, ["GK"], 86],
    ["Hakimi", 2, ["RB", "RWB"], 88],
    ["Saïss", 6, ["CB"], 84],
    ["Aguerd", 5, ["CB"], 84],
    ["Mazraoui", 3, ["RB", "LB"], 83],
    ["Amrabat", 4, ["DM"], 86],
    ["Ounahi", 8, ["CM"], 82],
    ["Ziyech", 7, ["RW", "AM"], 86],
    ["Boufal", 17, ["LW", "AM"], 82],
    ["En-Nesyri", 19, ["ST"], 84],
    ["Amallah", 15, ["AM", "CM"], 80],
    ["Dari", 18, ["CB"], 80],
  ]),
  squad("Uruguay", 2010, [
    ["Muslera", 1, ["GK"], 86],
    ["M. Pereira", 16, ["RB"], 82],
    ["Godín", 3, ["CB"], 88],
    ["Lugano", 2, ["CB"], 84],
    ["Cáceres", 4, ["LB", "CB"], 82],
    ["Pérez", 15, ["DM"], 82],
    ["Arevalo", 17, ["DM"], 80],
    ["Diego Forlán", 10, ["ST", "AM"], 90],
    ["Cavani", 7, ["ST"], 86],
    ["Suárez", 9, ["ST"], 90],
    ["Álvaro Pereira", 11, ["LB", "LM"], 82],
  ]),
  squad("Germany", 1990, [
    ["Illgner", 1, ["GK"], 86],
    ["Berthold", 2, ["RB", "CB"], 84],
    ["Kohler", 4, ["CB"], 88],
    ["Augsenthaler", 5, ["CB"], 86],
    ["Brehme", 3, ["LB", "RB"], 90],
    ["Buchwald", 6, ["CB", "DM"], 84],
    ["Häßler", 8, ["AM", "CM"], 87],
    ["Matthäus", 10, ["CM", "DM", "AM"], 94],
    ["Littbarski", 7, ["RW", "AM"], 88],
    ["Klinsmann", 18, ["ST"], 90],
    ["Völler", 9, ["ST"], 89],
  ]),
  squad("Italy", 1982, [
    ["Zoff", 1, ["GK"], 92],
    ["Gentile", 6, ["RB", "CB"], 88],
    ["Scirea", 7, ["CB"], 91],
    ["Collovati", 5, ["CB"], 85],
    ["Cabrini", 3, ["LB"], 88],
    ["Tardelli", 14, ["CM"], 90],
    ["Oriali", 13, ["DM", "CM"], 85],
    ["Antognoni", 10, ["AM"], 87],
    ["Conti", 16, ["RW"], 86],
    ["Rossi", 20, ["ST"], 91],
    ["Graziani", 19, ["ST"], 84],
  ]),
  squad("England", 2018, [
    ["Pickford", 1, ["GK"], 84],
    ["Walker", 2, ["RB", "CB"], 86],
    ["Stones", 5, ["CB"], 85],
    ["Maguire", 6, ["CB"], 84],
    ["Young", 3, ["LB", "LM"], 80],
    ["Henderson", 8, ["CM", "DM"], 84],
    ["Alli", 10, ["AM", "CM"], 84],
    ["Lingard", 7, ["AM", "RW"], 82],
    ["Sterling", 10, ["LW", "ST"], 88],
    ["Kane", 9, ["ST"], 91],
    ["Rashford", 11, ["LW", "ST"], 85],
    ["Trippier", 12, ["RB"], 84],
  ]),
  squad("Belgium", 2018, [
    ["Courtois", 1, ["GK"], 91],
    ["Meunier", 15, ["RB"], 82],
    ["Alderweireld", 2, ["CB"], 86],
    ["Kompany", 4, ["CB"], 86],
    ["Vertonghen", 5, ["CB", "LB"], 86],
    ["Witsel", 6, ["DM"], 85],
    ["De Bruyne", 7, ["AM", "CM"], 93],
    ["Hazard", 10, ["LW", "AM"], 93],
    ["Mertens", 14, ["ST", "RW"], 86],
    ["Lukaku", 9, ["ST"], 88],
    ["Carrasco", 11, ["LW"], 83],
    ["Fellaini", 8, ["CM"], 82],
  ]),
  squad("Spain", 2022, [
    ["Simón", 23, ["GK"], 84],
    ["Carvajal", 2, ["RB"], 86],
    ["Rodri", 16, ["DM", "CB"], 90],
    ["Laporte", 14, ["CB"], 86],
    ["Alba", 18, ["LB"], 84],
    ["Busquets", 5, ["DM"], 86],
    ["Pedri", 26, ["CM", "AM"], 88],
    ["Gavi", 9, ["CM"], 84],
    ["Olmo", 21, ["AM", "LW"], 86],
    ["Morata", 7, ["ST"], 84],
    ["Williams", 12, ["RW", "ST"], 84],
    ["Asensio", 10, ["RW", "AM"], 83],
  ]),
  squad("Colombia", 2014, [
    ["Ospina", 1, ["GK"], 84],
    ["Zúñiga", 18, ["RB"], 82],
    ["Yepes", 2, ["CB"], 82],
    ["Zapata", 3, ["CB"], 83],
    ["Armero", 7, ["LB"], 82],
    ["Sánchez", 6, ["DM", "CM"], 84],
    ["Guarín", 13, ["CM"], 83],
    ["Rodríguez", 10, ["AM", "CM"], 90],
    ["Cuadrado", 11, ["RW"], 86],
    ["Gutiérrez", 19, ["ST", "AM"], 82],
    ["Martínez", 21, ["ST"], 84],
    ["Ramos", 9, ["ST"], 82],
  ]),
  squad("Japan", 2022, [
    ["Gonda", 12, ["GK"], 80],
    ["Yamane", 2, ["RB"], 80],
    ["Yoshida", 22, ["CB"], 82],
    ["Itakura", 4, ["CB"], 82],
    ["Nagatomo", 5, ["LB"], 80],
    ["Endo", 6, ["DM"], 84],
    ["Tanaka", 17, ["CM"], 82],
    ["Kamada", 15, ["AM"], 83],
    ["Ito", 14, ["RW"], 84],
    ["Doan", 8, ["RW", "AM"], 82],
    ["Maeda", 25, ["ST"], 80],
    ["Mitoma", 9, ["LW"], 84],
  ]),
  squad("USA", 2022, [
    ["Turner", 1, ["GK"], 84],
    ["Dest", 2, ["RB", "LB"], 82],
    ["Zimmerman", 3, ["CB"], 80],
    ["Ream", 13, ["CB"], 80],
    ["Robinson", 5, ["LB"], 82],
    ["Adams", 4, ["DM"], 84],
    ["McKennie", 8, ["CM"], 83],
    ["Musah", 6, ["CM"], 81],
    ["Weah", 21, ["RW", "ST"], 82],
    ["Pulisic", 10, ["LW", "AM"], 86],
    ["Sargent", 24, ["ST"], 80],
    ["Reyna", 7, ["AM"], 82],
  ]),
  squad("Brazil", 1994, [
    ["Taffarel", 1, ["GK"], 88],
    ["Jorginho", 2, ["RB"], 86],
    ["Aldair", 3, ["CB"], 88],
    ["Márcio Santos", 15, ["CB"], 84],
    ["Branco", 6, ["LB"], 84],
    ["Dunga", 8, ["DM"], 88],
    ["Mauro Silva", 5, ["DM"], 87],
    ["Mazinho", 16, ["CM"], 84],
    ["Zinho", 9, ["AM", "CM"], 84],
    ["Romário", 11, ["ST"], 95],
    ["Bebeto", 7, ["ST"], 90],
    ["Rai", 10, ["AM"], 85],
  ]),
  squad("France", 2022, [
    ["Lloris", 1, ["GK"], 86],
    ["Pavard", 2, ["RB"], 83],
    ["Varane", 4, ["CB"], 88],
    ["Upamecano", 18, ["CB"], 84],
    ["T. Hernández", 22, ["LB"], 86],
    ["Tchouaméni", 8, ["DM"], 86],
    ["Rabiot", 14, ["CM"], 84],
    ["Griezmann", 7, ["AM", "ST"], 88],
    ["Dembélé", 11, ["RW"], 86],
    ["Mbappé", 10, ["ST", "LW"], 96],
    ["Giroud", 9, ["ST"], 84],
    ["Camavinga", 6, ["CM", "LB"], 84],
  ]),
  squad("Brazil", 1958, [
    ["Gilmar", 3, ["GK"], 88],
    ["Djalma Santos", 4, ["RB"], 90],
    ["Bellini", 2, ["CB"], 86],
    ["Orlando", 5, ["CB"], 84],
    ["Nílton Santos", 6, ["LB"], 92],
    ["Zito", 8, ["CM", "DM"], 88],
    ["Didi", 10, ["CM", "AM"], 93],
    ["Garrincha", 7, ["RW"], 96],
    ["Vavá", 9, ["ST"], 90],
    ["Pelé", 10, ["ST", "AM"], 96],
    ["Zagallo", 11, ["LW"], 88],
  ]),
  squad("Argentina", 1978, [
    ["Fillol", 5, ["GK"], 88],
    ["Olguín", 15, ["RB"], 82],
    ["Passarella", 7, ["CB"], 91],
    ["Galván", 8, ["CB"], 84],
    ["Tarantini", 20, ["LB"], 84],
    ["Ardiles", 2, ["CM"], 88],
    ["Gallego", 6, ["DM"], 84],
    ["Kempes", 10, ["ST", "AM"], 93],
    ["Bertoni", 4, ["RW"], 86],
    ["Luque", 14, ["ST"], 86],
    ["Ortiz", 16, ["LW"], 82],
  ]),
  squad("Netherlands", 2010, [
    ["Stekelenburg", 1, ["GK"], 84],
    ["Van der Wiel", 2, ["RB"], 80],
    ["Heitinga", 3, ["CB"], 84],
    ["Mathijsen", 4, ["CB"], 82],
    ["Van Bronckhorst", 5, ["LB"], 86],
    ["Van Bommel", 6, ["DM"], 86],
    ["Sneijder", 10, ["AM", "CM"], 92],
    ["Kuyt", 7, ["RW", "ST"], 84],
    ["Robben", 11, ["RW"], 92],
    ["Van Persie", 9, ["ST"], 90],
    ["Afellay", 8, ["AM", "LW"], 82],
  ]),
  squad("Senegal", 2002, [
    ["Sylva", 1, ["GK"], 82],
    ["Daf", 2, ["RB"], 80],
    ["Coly", 4, ["CB"], 80],
    ["Diawara", 13, ["CB"], 80],
    ["Diao", 6, ["DM", "CM"], 82],
    ["Cissé", 10, ["CM"], 82],
    ["Fadiga", 11, ["AM", "LW"], 84],
    ["Diouf", 9, ["ST", "RW"], 86],
    ["Camara", 7, ["ST"], 82],
    ["H. Camara", 12, ["LW", "ST"], 80],
    ["N'Diaye", 15, ["CB"], 78],
  ]),
];

export const ALL_PLAYERS: Player[] = SQUADS.flatMap((s) => s.players);

export function randomSquad(excludeIds: string[] = [], pool: PoolId = "world"): Squad {
  if (pool === "club") return randomClubSquad(excludeIds);
  const filtered = SQUADS.filter((s) => !excludeIds.includes(s.id));
  const source = filtered.length ? filtered : SQUADS;
  return source[Math.floor(Math.random() * source.length)]!;
}

export function otherYears(squad: Squad, excludeIds: string[] = [], pool: PoolId = "world"): Squad[] {
  const list = pool === "club" ? CLUB_SQUADS : SQUADS;
  return list.filter(
    (s) => s.nation === squad.nation && s.id !== squad.id && !excludeIds.includes(s.id),
  );
}

export { CLUB_SQUADS };
