/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ClubFriendsRouteImport } from './routes/club_.friends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubFriendsRoute = ClubFriendsRouteImport.update({
  id: '/club_/friends',
  path: '/club/friends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/club': typeof ClubRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/friends': typeof ClubFriendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/club': typeof ClubRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/friends': typeof ClubFriendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/club': typeof ClubRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club_/friends': typeof ClubFriendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/club'
    | '/contact'
    | '/friends'
    | '/how-to-play'
    | '/privacy'
    | '/terms'
    | '/api/rtc'
    | '/club/friends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/club'
    | '/contact'
    | '/friends'
    | '/how-to-play'
    | '/privacy'
    | '/terms'
    | '/api/rtc'
    | '/club/friends'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/club'
    | '/contact'
    | '/friends'
    | '/how-to-play'
    | '/privacy'
    | '/terms'
    | '/api/rtc'
    | '/club_/friends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClubRoute: typeof ClubRoute
  ContactRoute: typeof ContactRoute
  FriendsRoute: typeof FriendsRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ClubFriendsRoute: typeof ClubFriendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club_/friends': {
      id: '/club_/friends'
      path: '/club/friends'
      fullPath: '/club/friends'
      preLoaderRoute: typeof ClubFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClubRoute: ClubRoute,
  ContactRoute: ContactRoute,
  FriendsRoute: FriendsRoute,
  HowToPlayRoute: HowToPlayRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ClubFriendsRoute: ClubFriendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
