/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ClubSeasonsRouteImport } from './routes/club-seasons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorldCupsRouteImport } from './routes/world-cups'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ClubFriendsRouteImport } from './routes/club_.friends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubSeasonsRoute = ClubSeasonsRouteImport.update({
  id: '/club-seasons',
  path: '/club-seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldCupsRoute = WorldCupsRouteImport.update({
  id: '/world-cups',
  path: '/world-cups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubFriendsRoute = ClubFriendsRouteImport.update({
  id: '/club_/friends',
  path: '/club/friends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/club': typeof ClubRoute
  '/club-seasons': typeof ClubSeasonsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/friends': typeof FriendsRoute
  '/guides': typeof GuidesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/world-cups': typeof WorldCupsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/friends': typeof ClubFriendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/club': typeof ClubRoute
  '/club-seasons': typeof ClubSeasonsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/friends': typeof FriendsRoute
  '/guides': typeof GuidesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/world-cups': typeof WorldCupsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club/friends': typeof ClubFriendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/club': typeof ClubRoute
  '/club-seasons': typeof ClubSeasonsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/friends': typeof FriendsRoute
  '/guides': typeof GuidesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/world-cups': typeof WorldCupsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/club_/friends': typeof ClubFriendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/club'
    | '/club-seasons'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/friends'
    | '/guides'
    | '/how-to-play'
    | '/privacy'
    | '/ratings'
    | '/sources'
    | '/terms'
    | '/world-cups'
    | '/api/rtc'
    | '/club/friends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/club'
    | '/club-seasons'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/friends'
    | '/guides'
    | '/how-to-play'
    | '/privacy'
    | '/ratings'
    | '/sources'
    | '/terms'
    | '/world-cups'
    | '/api/rtc'
    | '/club/friends'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/club'
    | '/club-seasons'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/friends'
    | '/guides'
    | '/how-to-play'
    | '/privacy'
    | '/ratings'
    | '/sources'
    | '/terms'
    | '/world-cups'
    | '/api/rtc'
    | '/club_/friends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClubRoute: typeof ClubRoute
  ClubSeasonsRoute: typeof ClubSeasonsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  FriendsRoute: typeof FriendsRoute
  GuidesRoute: typeof GuidesRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PrivacyRoute: typeof PrivacyRoute
  RatingsRoute: typeof RatingsRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
  WorldCupsRoute: typeof WorldCupsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ClubFriendsRoute: typeof ClubFriendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club-seasons': {
      id: '/club-seasons'
      path: '/club-seasons'
      fullPath: '/club-seasons'
      preLoaderRoute: typeof ClubSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-cups': {
      id: '/world-cups'
      path: '/world-cups'
      fullPath: '/world-cups'
      preLoaderRoute: typeof WorldCupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club_/friends': {
      id: '/club_/friends'
      path: '/club/friends'
      fullPath: '/club/friends'
      preLoaderRoute: typeof ClubFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClubRoute: ClubRoute,
  ClubSeasonsRoute: ClubSeasonsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  FriendsRoute: FriendsRoute,
  GuidesRoute: GuidesRoute,
  HowToPlayRoute: HowToPlayRoute,
  PrivacyRoute: PrivacyRoute,
  RatingsRoute: RatingsRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
  WorldCupsRoute: WorldCupsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ClubFriendsRoute: ClubFriendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
